Fix

diff --git a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
--- a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
+++ b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
@@ -409,7 +409,7 @@ List extractReleaseTags(final String fileContent) {
 def getStageOfUpgradeJob(job) {
     return {
         stage("Upgrade Verrazzano from version ${job[0]} to  ${job[1].replace('_', " ")}"){
-            retry(count: JOB_PROMOTION_RETRIES) {
+           // retry(count: JOB_PROMOTION_RETRIES) {
                 script {
                     try {
                         echo "Running upgrade job from version ${job[0]} to ${job[1].replace('_', " ")}"
@@ -429,14 +429,19 @@ def getStageOfUpgradeJob(job) {
                             booleanParam(name: 'EMIT_METRICS', value: params.EMIT_METRICS)
                         ],  wait: true, propagate: true
                     }catch(err){
-                        catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
+                        retry(2){
+                            echo "Caught: ${err}"
+                            echo "Retrying..."
+                        }
+                        /*catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
                             echo "Caught: ${err}"
                             sh "exit 1"
-                        }
+                        }*/
                         // currentBuild.result = 'FAILURE'
+                        sh "exit 1"
                     }
                 }
-            }
+           // }
         }
     }
 }
