Update JenkinsfileTestTriggerMinorRelease

diff --git a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
--- a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
+++ b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
@@ -82,6 +82,7 @@ pipeline {
         PROMETHEUS_GW_URL = credentials('prometheus-dev-url')
         SERVICE_KEY = credentials('PAGERDUTY_SERVICE_KEY')
         TARGET_UPGRADE_VERSION = "current_branch"
+        GIT_RELEASE_COMMIT_ID = ""
     }
 
     stages {
@@ -149,39 +150,7 @@ pipeline {
            
         stage ('Upgrade every release to next Minor Release') {
             parallel {
-                stage('Upgrade Verrazzano from version current branch to master'){
-                    when {
-                       expression { CLEAN_BRANCH_NAME != 'master' }
-                    }
-                    steps{
-                        script{
-                            try{
-                                echo "Running upgrade job from version current branch to master"
-                                retry(count: JOB_PROMOTION_RETRIES) {
-                                    def jobStatus =  build job: "/verrazzano-upgrade-path-tests/${CLEAN_BRANCH_NAME}",
-                                    parameters: [
-                                                string(name: 'GIT_COMMIT_TO_USE', value: params.GIT_COMMIT_TO_USE),
-                                                string(name: 'VERSION_FOR_INSTALL', value: "current_branch" ),
-                                                string(name: 'VERSION_FOR_UPGRADE', value: "master"),
-                                                string(name: 'VZ_INSTALL_CONFIG', value: params.VZ_INSTALL_CONFIG),
-                                                string(name: 'IS_TRIGGERED_MANUALLY', value: "NO"),
-                                                string(name: 'VERRAZZANO_OPERATOR_IMAGE', value: params.VERRAZZANO_OPERATOR_IMAGE),
-                                                string(name: 'WILDCARD_DNS_DOMAIN', value: params.WILDCARD_DNS_DOMAIN),
-                                                string(name: 'TAGGED_TESTS', value: params.TAGGED_TESTS),
-                                                string(name: 'INCLUDED_TESTS', value: params.INCLUDED_TESTS),
-                                                string(name: 'EXCLUDED_TESTS', value: params.EXCLUDED_TESTS),
-                                                string(name: 'CONSOLE_REPO_BRANCH', value: params.CONSOLE_REPO_BRANCH),
-                                            ],  wait: true, propagate: true
-                                        }
-                                }catch(err){
-                                    catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
-                                        echo "Caught: ${err}"
-                                        sh "exit 1"
-                                    }
-                                }
-                        }
-                    }
-                }
+                
                 stage('Compute required N Upgrade Jobs') {
                 steps {
                     script {
@@ -206,6 +175,16 @@ pipeline {
                         }
                         echo "List of Releases after excluding the user requested releases: ${finalReleaseList}"
                         listOfUpgradeJobs = addTargetUpgradeVersion(finalReleaseList)
+                        
+                        minorReleaseList = getTipOfReleaseBranches(finalReleaseList)
+                        for(release in minorReleaseList){
+                            RELEASE = release
+                            sh """
+                                ${GIT_RELEASE_COMMIT_ID} = $(git rev-parse release-${RELEASE})
+                                echo "release-${RELEASE}:${GIT_RELEASE_COMMIT_ID}" >> ${workspace}/releaseAndCommits.txt
+                            """
+                        }
+                        sh "cat ${workspace}/releaseAndCommits.txt"
                         def NJObs = Integer.parseInt(params.N_JOBS_FOR_EACH_BATCH)
                         echo "Number of jobs to be run in parallel : ${params.N_JOBS_FOR_EACH_BATCH}"
                         def k = 0
@@ -392,6 +371,16 @@ List extractReleaseTags(final String fileContent) {
     return releases
 }
 
+def getTipOfReleaseBranches(List releaseList){
+    List minorReleases = []
+    for(tag in gitTags){
+        if (tag[-1] == "0"){
+            minorReleases.add(tag[1..3])
+        }
+    }
+    return minorReleases
+}
+
 def getStageOfUpgradeJob(job) {
     return {
         stage("Upgrade Verrazzano from version ${job[0]} to  ${job[1].replace('_', " ")}"){
@@ -418,6 +407,44 @@ def getStageOfUpgradeJob(job) {
                     catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
                         echo "Caught: ${err}"
                         sh "exit 1"
+                    }
+                }
+            }
+        }
+    }
+}
+
+def getTipOfBranchToMasterJob(tipOfBranches) {
+    return {
+        stage('Upgrade Verrazzano from version current branch to master') {
+            when {
+                expression { CLEAN_BRANCH_NAME != 'master' }
+            }
+            steps {
+                script{
+                    try{
+                        echo "Running upgrade job from version current branch to master"
+                        retry(count: JOB_PROMOTION_RETRIES) {
+                            def jobStatus =  build job: "/verrazzano-upgrade-path-tests/${CLEAN_BRANCH_NAME}",
+                            parameters: [
+                                string(name: 'GIT_COMMIT_TO_USE', value: params.GIT_COMMIT_TO_USE),
+                                string(name: 'VERSION_FOR_INSTALL', value: "current_branch" ),
+                                string(name: 'VERSION_FOR_UPGRADE', value: "master"),
+                                string(name: 'VZ_INSTALL_CONFIG', value: params.VZ_INSTALL_CONFIG),
+                                string(name: 'IS_TRIGGERED_MANUALLY', value: "NO"),
+                                string(name: 'VERRAZZANO_OPERATOR_IMAGE', value: params.VERRAZZANO_OPERATOR_IMAGE),
+                                string(name: 'WILDCARD_DNS_DOMAIN', value: params.WILDCARD_DNS_DOMAIN),
+                                string(name: 'TAGGED_TESTS', value: params.TAGGED_TESTS),
+                                string(name: 'INCLUDED_TESTS', value: params.INCLUDED_TESTS),
+                                string(name: 'EXCLUDED_TESTS', value: params.EXCLUDED_TESTS),
+                                string(name: 'CONSOLE_REPO_BRANCH', value: params.CONSOLE_REPO_BRANCH),
+                            ],  wait: true, propagate: true
+                        }
+                    } catch(err) {
+                        catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE') {
+                            echo "Caught: ${err}"
+                            sh "exit 1"
+                        }
                     }
                 }
             }
