Fix blue ocean stage failure issue refactore the code for readability

diff --git a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
--- a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
+++ b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
@@ -3,8 +3,8 @@
 
 def agentLabel = env.JOB_NAME.contains('master') ? "phxlarge" : "VM.Standard2.8"
 
-def allReleasesToRCJobs
-def allReleasesToRCStagesMap
+def listOfUpgradeJobs
+def upgradeJobsStageMapping
 def branchSpecificSchedule = getCronSchedule()
 pipeline {
     options {
@@ -153,20 +153,20 @@ pipeline {
                         final String fileContent = readFile(file: "${workspace}/tags.txt")
                         final List gitTags = extractReleaseTags(fileContent)
                         echo "gitTags = ${gitTags}"
-                        allReleasesToRCJobs = addTargetUpgradeVersion(gitTags)
+                        listOfUpgradeJobs = addTargetUpgradeVersion(gitTags)
                         def NJObs = Integer.parseInt(params.N_JOBS_FOR_EACH_BATCH)
                         echo "Number of jobs to be run in parallel : ${params.N_JOBS_FOR_EACH_BATCH}"
                         def k = 0
                         def  mapOfJobsInBatches = []
-                        allReleasesToRCStagesMap = [:]
-                        for(int i=0;i<allReleasesToRCJobs.size();i++){
+                        upgradeJobsStageMapping = [:]
+                        for(int i=0;i<listOfUpgradeJobs.size();i++){
                             if(k<NJObs){
-                                allReleasesToRCStagesMap.put(allReleasesToRCJobs.get(i),allReleasesToRCStage(allReleasesToRCJobs.get(i)))
+                                upgradeJobsStageMapping.put(listOfUpgradeJobs.get(i),getStageOfUpgradeJob(listOfUpgradeJobs.get(i)))
                                 k++;
                             }
-                            if(k==NJObs || i == allReleasesToRCJobs.size()-1){
-                                mapOfJobsInBatches.add(allReleasesToRCStagesMap)
-                                allReleasesToRCStagesMap = [:]
+                            if(k==NJObs || i == listOfUpgradeJobs.size()-1){
+                                mapOfJobsInBatches.add(upgradeJobsStageMapping)
+                                upgradeJobsStageMapping = [:]
                                 k = 0;
                             }
                     }
@@ -175,7 +175,7 @@ pipeline {
                         sleep 5
                         parallel batch
                     }
-                    //parallel allReleasesToRCStagesMap
+                    //parallel upgradeJobsStageMapping
                      }
                    }
                 }
@@ -389,11 +389,11 @@ List extractReleaseTags(final String fileContent) {
     return releases
 }
 
-def allReleasesToRCStage(job) {
+def getStageOfUpgradeJob(job) {
     return {
-        try {
-            stage("Upgrade Verrazzano from version ${job[0]} to  ${job[1]}"){
-                script {
+        stage("Upgrade Verrazzano from version ${job[0]} to  ${job[1]}"){
+            script {
+                try {
                     echo "Running upgrade job from version ${job[0]} to ${job[1]}"
                     def jobStatus =  build job: "/verrazzano-upgrade-path-tests/${CLEAN_BRANCH_NAME}",
                     parameters: [
@@ -407,11 +407,14 @@ def allReleasesToRCStage(job) {
                         string(name: 'EXCLUDED_TESTS', value: params.EXCLUDED_TESTS),
                         booleanParam(name: 'EMIT_METRICS', value: params.EMIT_METRICS)
                     ],  wait: true, propagate: true
+                }catch(err){
+                    catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
+                        echo "Caught: ${err}"
+                        sh "exit 1"
+                    }
+                   // currentBuild.result = 'FAILURE'
                 }
             }
-        }catch(err){
-            echo "Caught: ${err}"
-            currentBuild.result = 'FAILURE'
         }
     }
 }
