enable propagate

diff --git a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
--- a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
+++ b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
@@ -433,9 +433,25 @@ def getStageOfUpgradeJob(job) {
                 }catch(err){
                     catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
                         echo "Caught: ${err}"
-                        sh "exit 1"
+                        results = jobStatus.getResult()
+                        echo "Build results: ${results}"
+                        //sh "exit 1"
                     }
                    // currentBuild.result = 'FAILURE'
+                }
+            }
+            post {
+                always {
+                    echo "Build results in post: ${results.toString()} "
+                }
+                success {
+                    echo "Build is successful"
+                }
+                unstable {
+                    echo "Build is unstable"
+                }
+                failure {
+                    echo "Build has failed"
                 }
             }
         }
