Fix upgrade from tip of release branches to master (#6250)

diff --git a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
--- a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
+++ b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
@@ -437,33 +437,31 @@ def getStageOfUpgradeJob(job) {
 def getTipOfBranchToMasterJob(String release, String commitSHA) {
     return {
         stage("Upgrade Verrazzano from tip of ${release} to master") {
-            if( CLEAN_BRANCH_NAME != 'master') {
-                    script{
-                        try{
-                            echo "Running upgrade job from version ${release}-${commitSHA} to master"
-                            retry(count: JOB_PROMOTION_RETRIES) {
-                                def jobStatus =  build job: "/verrazzano-upgrade-path-tests/${CLEAN_BRANCH_NAME}",
-                                parameters: [
-                                    string(name: 'GIT_COMMIT_TO_USE', value: "${commitSHA}"),
-                                    string(name: 'VERSION_FOR_INSTALL', value: "${release}" ),
-                                    string(name: 'VERSION_FOR_UPGRADE', value: "master"),
-                                    string(name: 'VZ_INSTALL_CONFIG', value: params.VZ_INSTALL_CONFIG),
-                                    string(name: 'IS_TRIGGERED_MANUALLY', value: "NO"),
-                                    string(name: 'VERRAZZANO_OPERATOR_IMAGE', value: params.VERRAZZANO_OPERATOR_IMAGE),
-                                    string(name: 'WILDCARD_DNS_DOMAIN', value: params.WILDCARD_DNS_DOMAIN),
-                                    string(name: 'TAGGED_TESTS', value: params.TAGGED_TESTS),
-                                    string(name: 'INCLUDED_TESTS', value: params.INCLUDED_TESTS),
-                                    string(name: 'EXCLUDED_TESTS', value: params.EXCLUDED_TESTS),
-                                    string(name: 'CONSOLE_REPO_BRANCH', value: params.CONSOLE_REPO_BRANCH)
-                                ],  wait: true, propagate: true
-                            }
-                        } catch(err) {
-                            catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE') {
-                                echo "Caught: ${err}"
-                                sh "exit 1"
-                            }
-                        }
-                    } 
+            script{
+                try{
+                    echo "Running upgrade job from version ${release}-${commitSHA} to master"
+                    retry(count: JOB_PROMOTION_RETRIES) {
+                        def jobStatus =  build job: "/verrazzano-upgrade-path-tests/${CLEAN_BRANCH_NAME}",
+                        parameters: [
+                            string(name: 'GIT_COMMIT_TO_USE', value: "${commitSHA}"),
+                            string(name: 'VERSION_FOR_INSTALL', value: "${release}" ),
+                            string(name: 'VERSION_FOR_UPGRADE', value: "master"),
+                            string(name: 'VZ_INSTALL_CONFIG', value: params.VZ_INSTALL_CONFIG),
+                            string(name: 'IS_TRIGGERED_MANUALLY', value: "NO"),
+                            string(name: 'VERRAZZANO_OPERATOR_IMAGE', value: params.VERRAZZANO_OPERATOR_IMAGE),
+                            string(name: 'WILDCARD_DNS_DOMAIN', value: params.WILDCARD_DNS_DOMAIN),
+                            string(name: 'TAGGED_TESTS', value: params.TAGGED_TESTS),
+                            string(name: 'INCLUDED_TESTS', value: params.INCLUDED_TESTS),
+                            string(name: 'EXCLUDED_TESTS', value: params.EXCLUDED_TESTS),
+                            string(name: 'CONSOLE_REPO_BRANCH', value: params.CONSOLE_REPO_BRANCH)
+                        ],  wait: true, propagate: true
+                    }
+                } catch(err) {
+                    catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE') {
+                        echo "Caught: ${err}"
+                        sh "exit 1"
+                    }
+                }
             }
         }
     }
