Trying post steps of minor release pipelien

diff --git a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
--- a/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
+++ b/ci/upgrade-paths/JenkinsfileTestTriggerMinorRelease
@@ -429,13 +429,29 @@ def getStageOfUpgradeJob(job) {
                         string(name: 'EXCLUDED_TESTS', value: params.EXCLUDED_TESTS),
                         string(name: 'CONSOLE_REPO_BRANCH', value: params.CONSOLE_REPO_BRANCH),
                         booleanParam(name: 'EMIT_METRICS', value: params.EMIT_METRICS)
-                    ],  wait: true, propagate: true
+                    ],  wait: true, propagate: false
                 }catch(err){
                     catchError(message: "${STAGE_NAME} Failed with ${err}", buildResult: 'FAILURE', stageResult: 'FAILURE'){
                         echo "Caught: ${err}"
-                        sh "exit 1"
+                        results = jobStatus.getResult()
+                        echo "Build results: ${results}"
+                        //sh "exit 1"
                     }
                    // currentBuild.result = 'FAILURE'
+                }
+            }
+            post {
+                always {
+                    echo "Build results in post: ${results.toString()} "
+                }
+                success {
+                    echo "Build is successful"
+                }
+                unstable {
+                    echo "Build is unstable"
+                }
+                failure {
+                    echo "Build has failed"
                 }
             }
         }
