Removed redundant steps

diff --git a/ci/multicluster/Jenkinsfile b/ci/multicluster/Jenkinsfile
--- a/ci/multicluster/Jenkinsfile
+++ b/ci/multicluster/Jenkinsfile
@@ -1460,80 +1460,75 @@ def verifyUpgrade() {
 }
 
 def cleanWorkspaceAndCheckout() {
-    steps {
-        sh """
-            echo "${NODE_LABELS}"
-        """
-
-        script {
-            EFFECTIVE_DUMP_K8S_CLUSTER_ON_SUCCESS = getEffectiveDumpOnSuccess()
-            if (params.GIT_COMMIT_TO_USE == "NONE") {
-                echo "Specific GIT commit was not specified, use current head"
-                def scmInfo = checkout scm
-                env.GIT_COMMIT = scmInfo.GIT_COMMIT
-                env.GIT_BRANCH = scmInfo.GIT_BRANCH
-            } else {
-                echo "SCM checkout of ${params.GIT_COMMIT_TO_USE}"
-                def scmInfo = checkout([
-                    $class: 'GitSCM',
-                    branches: [[name: params.GIT_COMMIT_TO_USE]],
-                    doGenerateSubmoduleConfigurations: false,
-                    extensions: [],
-                    submoduleCfg: [],
-                    userRemoteConfigs: [[url: env.SCM_VERRAZZANO_GIT_URL]]])
-                env.GIT_COMMIT = scmInfo.GIT_COMMIT
-                env.GIT_BRANCH = scmInfo.GIT_BRANCH
-                // If the commit we were handed is not what the SCM says we are using, fail
-                if (!env.GIT_COMMIT.equals(params.GIT_COMMIT_TO_USE)) {
-                    echo "SCM didn't checkout the commit we expected. Expected: ${params.GIT_COMMIT_TO_USE}, Found: ${scmInfo.GIT_COMMIT}"
-                    exit 1
-                }
+    sh """
+        echo "${NODE_LABELS}"
+    """
+    script {
+        EFFECTIVE_DUMP_K8S_CLUSTER_ON_SUCCESS = getEffectiveDumpOnSuccess()
+        if (params.GIT_COMMIT_TO_USE == "NONE") {
+            echo "Specific GIT commit was not specified, use current head"
+            def scmInfo = checkout scm
+            env.GIT_COMMIT = scmInfo.GIT_COMMIT
+            env.GIT_BRANCH = scmInfo.GIT_BRANCH
+        } else {
+            echo "SCM checkout of ${params.GIT_COMMIT_TO_USE}"
+            def scmInfo = checkout([
+                $class: 'GitSCM',
+                branches: [[name: params.GIT_COMMIT_TO_USE]],
+                doGenerateSubmoduleConfigurations: false,
+                extensions: [],
+                submoduleCfg: [],
+                userRemoteConfigs: [[url: env.SCM_VERRAZZANO_GIT_URL]]])
+            env.GIT_COMMIT = scmInfo.GIT_COMMIT
+            env.GIT_BRANCH = scmInfo.GIT_BRANCH
+            // If the commit we were handed is not what the SCM says we are using, fail
+            if (!env.GIT_COMMIT.equals(params.GIT_COMMIT_TO_USE)) {
+                echo "SCM didn't checkout the commit we expected. Expected: ${params.GIT_COMMIT_TO_USE}, Found: ${scmInfo.GIT_COMMIT}"
+                exit 1
             }
-            echo "SCM checkout of ${env.GIT_BRANCH} at ${env.GIT_COMMIT}"
         }
-
-        sh """
-            cp -f "${NETRC_FILE}" $HOME/.netrc
-            chmod 600 $HOME/.netrc
-        """
-
-        script {
-            try {
+        echo "SCM checkout of ${env.GIT_BRANCH} at ${env.GIT_COMMIT}"
+    }
+    sh """
+        cp -f "${NETRC_FILE}" $HOME/.netrc
+        chmod 600 $HOME/.netrc
+    """
+    script {
+        try {
+            sh """
+                echo "${DOCKER_CREDS_PSW}" | docker login ${env.DOCKER_REPO} -u ${DOCKER_CREDS_USR} --password-stdin
+            """
+        } catch(error) {
+            echo "docker login failed, retrying after sleep"
+            retry(4) {
+                sleep(30)
                 sh """
                     echo "${DOCKER_CREDS_PSW}" | docker login ${env.DOCKER_REPO} -u ${DOCKER_CREDS_USR} --password-stdin
                 """
-            } catch(error) {
-                echo "docker login failed, retrying after sleep"
-                retry(4) {
-                    sleep(30)
-                    sh """
-                        echo "${DOCKER_CREDS_PSW}" | docker login ${env.DOCKER_REPO} -u ${DOCKER_CREDS_USR} --password-stdin
-                    """
-                }
             }
         }
-        sh """
-            rm -rf ${GO_REPO_PATH}/verrazzano
-            mkdir -p ${GO_REPO_PATH}/verrazzano
-            tar cf - . | (cd ${GO_REPO_PATH}/verrazzano/ ; tar xf -)
-        """
-        script {
-            def props = readProperties file: '.verrazzano-development-version'
-            VERRAZZANO_DEV_VERSION = props['verrazzano-development-version']
-            TIMESTAMP = sh(returnStdout: true, script: "date +%Y%m%d%H%M%S").trim()
-            SHORT_COMMIT_HASH = sh(returnStdout: true, script: "git rev-parse --short=8 HEAD").trim()
-            DOCKER_IMAGE_TAG = "${VERRAZZANO_DEV_VERSION}-${TIMESTAMP}-${SHORT_COMMIT_HASH}"
-            // update the description with some meaningful info
-            setDisplayName()
-            currentBuild.description = SHORT_COMMIT_HASH + " : " + env.GIT_COMMIT + " : " + params.GIT_COMMIT_TO_USE
+    }
+    sh """
+        rm -rf ${GO_REPO_PATH}/verrazzano
+        mkdir -p ${GO_REPO_PATH}/verrazzano
+        tar cf - . | (cd ${GO_REPO_PATH}/verrazzano/ ; tar xf -)
+    """
+    script {
+        def props = readProperties file: '.verrazzano-development-version'
+        VERRAZZANO_DEV_VERSION = props['verrazzano-development-version']
+        TIMESTAMP = sh(returnStdout: true, script: "date +%Y%m%d%H%M%S").trim()
+        SHORT_COMMIT_HASH = sh(returnStdout: true, script: "git rev-parse --short=8 HEAD").trim()
+        DOCKER_IMAGE_TAG = "${VERRAZZANO_DEV_VERSION}-${TIMESTAMP}-${SHORT_COMMIT_HASH}"
+        // update the description with some meaningful info
+        setDisplayName()
+        currentBuild.description = SHORT_COMMIT_HASH + " : " + env.GIT_COMMIT + " : " + params.GIT_COMMIT_TO_USE
 
-            if (params.TEST_ENV != "KIND") {
-                // derive the prefix for the OKE cluster
-                OKE_CLUSTER_PREFIX = sh(returnStdout: true, script: "${GO_REPO_PATH}/verrazzano/ci/scripts/derive_oke_cluster_name.sh").trim()
-            }
-            // Derive Kubernetes version, which is used to set the value for a label in the metrics emitted by the tests
-            env.K8S_VERSION_LABEL = "${params.TEST_ENV == 'KIND' ? params.KIND_CLUSTER_VERSION : sh(returnStdout: true, script: "${WORKSPACE}/ci/scripts/derive_kubernetes_version.sh ${params.OKE_CLUSTER_VERSION}").trim()}"
+        if (params.TEST_ENV != "KIND") {
+            // derive the prefix for the OKE cluster
+            OKE_CLUSTER_PREFIX = sh(returnStdout: true, script: "${GO_REPO_PATH}/verrazzano/ci/scripts/derive_oke_cluster_name.sh").trim()
         }
+        // Derive Kubernetes version, which is used to set the value for a label in the metrics emitted by the tests
+        env.K8S_VERSION_LABEL = "${params.TEST_ENV == 'KIND' ? params.KIND_CLUSTER_VERSION : sh(returnStdout: true, script: "${WORKSPACE}/ci/scripts/derive_kubernetes_version.sh ${params.OKE_CLUSTER_VERSION}").trim()}"
     }
 }
 
@@ -1551,7 +1546,7 @@ def configureOCIDNSResources() {
 }
 
 def runPostPipelineFailureScript() {
-script {
+    script {
     if ( fileExists(env.TESTS_EXECUTED_FILE) ) {
             dumpVerrazzanoSystemPods()
             dumpCattleSystemPods()
@@ -1571,7 +1566,6 @@ script {
     """
     archiveArtifacts artifacts: "**/*-operator.yaml,**/install-verrazzano.yaml,**/kube_config,**/coverage.html,**/logs/**,**/build/resources/**,**/verrazzano_images.txt,**/*-cluster-dump*/**,**/test-cluster-dumps/**,**/${TEST_REPORT}", allowEmptyArchive: true
     junit testResults: "**/${TEST_REPORT}", allowEmptyResults: true
-
     script {
             // Create a dictionary of Verrazzano uninstall steps to be executed in parallel
             // - the first one will always be the Admin cluster
@@ -1588,7 +1582,6 @@ script {
             }
             parallel verrazzanoUninstallStages
     }
-
     script {
         // Create a dictionary of Verrazzano verify uninstall steps to be executed in parallel
         // - the first one will always be the Admin cluster
@@ -1604,7 +1597,6 @@ script {
         }
         parallel verifyUninstallStages
     }
-
     script {
         if (params.EMIT_METRICS) {
             withCredentials([usernameColonPassword(credentialsId: 'prometheus-credentials', variable: 'PROMETHEUS_CREDENTIALS')]) {
