Fix code in groovy method

diff --git a/ci/multicluster/Jenkinsfile b/ci/multicluster/Jenkinsfile
--- a/ci/multicluster/Jenkinsfile
+++ b/ci/multicluster/Jenkinsfile
@@ -317,16 +317,13 @@ pipeline {
         always {
             script {
                 if ( fileExists(env.TESTS_EXECUTED_FILE) ) {
-                    int clusterCount = params.TOTAL_CLUSTERS.toInteger() {
-                        for(int count=1; count<=clusterCount; count++) {
-                            dumpVerrazzanoSystemPods(count)
-                            dumpCattleSystemPods(count)
-                            dumpNginxIngressControllerLogs(count)
-                            dumpVerrazzanoPlatformOperatorLogs(count)
-                            dumpVerrazzanoApplicationOperatorLogs(count)
-                            dumpOamKubernetesRuntimeLogs(count)
-                            dumpVerrazzanoApiLogs(count)
-                        }
+                    dumpVerrazzanoSystemPods()
+                    dumpCattleSystemPods()
+                    dumpNginxIngressControllerLogs()
+                    dumpVerrazzanoPlatformOperatorLogs()
+                    dumpVerrazzanoApplicationOperatorLogs()
+                    dumpOamKubernetesRuntimeLogs()
+                    dumpVerrazzanoApiLogs()
                     }
                 }
             }
@@ -389,92 +386,127 @@ def dumpK8sCluster(dumpDirectory) {
     }
 }
 
-def dumpVerrazzanoSystemPods(count) {
-    sh """
-        export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
-        LOG_DIR="${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/cluster-$count"
-        mkdir -p ${LOG_DIR}
-        export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-system-pods.log"
-        ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -m "verrazzano system pods" || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-system-certs.log"
-        ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o cert -n verrazzano-system -m "verrazzano system certs" || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-system-kibana.log"
-        ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -r "vmi-system-kibana-*" -m "verrazzano system kibana log" -l -c kibana || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-system-es-master.log"
-        ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -r "vmi-system-es-master-*" -m "verrazzano system kibana log" -l -c es-master || echo "failed" > ${POST_DUMP_FAILED_FILE}
-    """
+def dumpVerrazzanoSystemPods() {
+    script {
+        int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+        for(int count=1; count<=clusterCount; count++) {
+            sh """
+                export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
+                LOG_DIR="${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/cluster-$count"
+                mkdir -p ${LOG_DIR}
+                export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-system-pods.log"
+                ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -m "verrazzano system pods" || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-system-certs.log"
+                ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o cert -n verrazzano-system -m "verrazzano system certs" || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-system-kibana.log"
+                ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -r "vmi-system-kibana-*" -m "verrazzano system kibana log" -l -c kibana || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-system-es-master.log"
+                ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -r "vmi-system-es-master-*" -m "verrazzano system kibana log" -l -c es-master || echo "failed" > ${POST_DUMP_FAILED_FILE}
+            """
+        }
+    }
 }
 
-def dumpCattleSystemPods(count) {
-    sh """
-        export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
-        LOG_DIR="${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/cluster-$count"
-        mkdir -p ${LOG_DIR}
-        export DIAGNOSTIC_LOG="${LOG_DIR}/cattle-system-pods.log"
-        ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n cattle-system -m "cattle system pods" || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        export DIAGNOSTIC_LOG="${LOG_DIR}/rancher.log"
-        ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n cattle-system -r "rancher-*" -m "Rancher logs" -l || echo "failed" > ${POST_DUMP_FAILED_FILE}
-    """
+def dumpCattleSystemPods() {
+    script {
+        int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+        for(int count=1; count<=clusterCount; count++) {
+            sh """
+                export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
+                LOG_DIR="${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/cluster-$count"
+                mkdir -p ${LOG_DIR}
+                export DIAGNOSTIC_LOG="${LOG_DIR}/cattle-system-pods.log"
+                ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n cattle-system -m "cattle system pods" || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                export DIAGNOSTIC_LOG="${LOG_DIR}/rancher.log"
+                ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n cattle-system -r "rancher-*" -m "Rancher logs" -l || echo "failed" > ${POST_DUMP_FAILED_FILE}
+            """
+        }
+    }
 }
 
-def dumpNginxIngressControllerLogs(count) {
-    sh """
-        export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
-        LOG_DIR="${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/cluster-$count"
-        mkdir -p ${LOG_DIR}
-        export DIAGNOSTIC_LOG="${LOG_DIR}/nginx-ingress-controller.log"
-        ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n ingress-nginx -r "nginx-ingress-controller-*" -m "Nginx Ingress Controller" -l || echo "failed" > ${POST_DUMP_FAILED_FILE}
-    """
+def dumpNginxIngressControllerLogs() {
+    script {
+        int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+        for(int count=1; count<=clusterCount; count++) {
+            sh """
+                export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
+                LOG_DIR="${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/cluster-$count"
+                mkdir -p ${LOG_DIR}
+                export DIAGNOSTIC_LOG="${LOG_DIR}/nginx-ingress-controller.log"
+                ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n ingress-nginx -r "nginx-ingress-controller-*" -m "Nginx Ingress Controller" -l || echo "failed" > ${POST_DUMP_FAILED_FILE}
+            """
+        }
+    }
 }
 
-def dumpVerrazzanoPlatformOperatorLogs(count) {
-    sh """
-        ## dump out verrazzano-platform-operator logs
-        export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
-        LOG_DIR="${WORKSPACE}/verrazzano-platform-operator/logs/cluster-$count"
-        mkdir -p ${LOG_DIR}
-        kubectl -n verrazzano-install logs --selector=app=verrazzano-platform-operator > ${LOG_DIR}/verrazzano-platform-operator-pod.log --tail -1 || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        kubectl -n verrazzano-install describe pod --selector=app=verrazzano-platform-operator > ${LOG_DIR}/verrazzano-platform-operator-pod.out || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        echo "verrazzano-platform-operator logs dumped to verrazzano-platform-operator-pod.log"
-        echo "verrazzano-platform-operator pod description dumped to verrazzano-platform-operator-pod.out"
-        echo "------------------------------------------"
-    """
+def dumpVerrazzanoPlatformOperatorLogs() {
+    script {
+        int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+        for(int count=1; count<=clusterCount; count++) {
+            sh """
+                ## dump out verrazzano-platform-operator logs
+                export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
+                LOG_DIR="${WORKSPACE}/verrazzano-platform-operator/logs/cluster-$count"
+                mkdir -p ${LOG_DIR}
+                kubectl -n verrazzano-install logs --selector=app=verrazzano-platform-operator > ${LOG_DIR}/verrazzano-platform-operator-pod.log --tail -1 || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                kubectl -n verrazzano-install describe pod --selector=app=verrazzano-platform-operator > ${LOG_DIR}/verrazzano-platform-operator-pod.out || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                echo "verrazzano-platform-operator logs dumped to verrazzano-platform-operator-pod.log"
+                echo "verrazzano-platform-operator pod description dumped to verrazzano-platform-operator-pod.out"
+                echo "------------------------------------------"
+            """
+        }
+    }
 }
 
-def dumpVerrazzanoApplicationOperatorLogs(count) {
-    sh """
-        ## dump out verrazzano-application-operator logs
-        export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
-        LOG_DIR="${WORKSPACE}/verrazzano-application-operator/logs/cluster-$count"
-        mkdir -p ${LOG_DIR}
-        kubectl -n verrazzano-system logs --selector=app=verrazzano-application-operator > ${LOG_DIR}/verrazzano-application-operator-pod.log --tail -1 || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        kubectl -n verrazzano-system describe pod --selector=app=verrazzano-application-operator > ${LOG_DIR}/verrazzano-application-operator-pod.out || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        echo "verrazzano-application-operator logs dumped to verrazzano-application-operator-pod.log"
-        echo "verrazzano-application-operator pod description dumped to verrazzano-application-operator-pod.out"
-        echo "------------------------------------------"
-    """
+def dumpVerrazzanoApplicationOperatorLogs() {
+    script {
+        int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+        for(int count=1; count<=clusterCount; count++) {
+            sh """
+                ## dump out verrazzano-application-operator logs
+                export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
+                LOG_DIR="${WORKSPACE}/verrazzano-application-operator/logs/cluster-$count"
+                mkdir -p ${LOG_DIR}
+                kubectl -n verrazzano-system logs --selector=app=verrazzano-application-operator > ${LOG_DIR}/verrazzano-application-operator-pod.log --tail -1 || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                kubectl -n verrazzano-system describe pod --selector=app=verrazzano-application-operator > ${LOG_DIR}/verrazzano-application-operator-pod.out || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                echo "verrazzano-application-operator logs dumped to verrazzano-application-operator-pod.log"
+                echo "verrazzano-application-operator pod description dumped to verrazzano-application-operator-pod.out"
+                echo "------------------------------------------"
+            """
+        }
+    }
 }
 
-def dumpOamKubernetesRuntimeLogs(count) {
-    sh """
-        ## dump out oam-kubernetes-runtime logs
-        export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
-        LOG_DIR="${WORKSPACE}/oam-kubernetes-runtime/logs/cluster-$count"
-        mkdir -p ${LOG_DIR}
-        kubectl -n verrazzano-system logs --selector=app.kubernetes.io/instance=oam-kubernetes-runtime > ${LOG_DIR}/oam-kubernetes-runtime-pod.log --tail -1 || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        kubectl -n verrazzano-system describe pod --selector=app.kubernetes.io/instance=oam-kubernetes-runtime > ${LOG_DIR}/oam-kubernetes-runtime-pod.out || echo "failed" > ${POST_DUMP_FAILED_FILE}
-        echo "verrazzano-application-operator logs dumped to oam-kubernetes-runtime-pod.log"
-        echo "verrazzano-application-operator pod description dumped to oam-kubernetes-runtime-pod.out"
-        echo "------------------------------------------"
-    """
+def dumpOamKubernetesRuntimeLogs() {
+    script {
+        int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+        for(int count=1; count<=clusterCount; count++) {
+            sh """
+                ## dump out oam-kubernetes-runtime logs
+                export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
+                LOG_DIR="${WORKSPACE}/oam-kubernetes-runtime/logs/cluster-$count"
+                mkdir -p ${LOG_DIR}
+                kubectl -n verrazzano-system logs --selector=app.kubernetes.io/instance=oam-kubernetes-runtime > ${LOG_DIR}/oam-kubernetes-runtime-pod.log --tail -1 || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                kubectl -n verrazzano-system describe pod --selector=app.kubernetes.io/instance=oam-kubernetes-runtime > ${LOG_DIR}/oam-kubernetes-runtime-pod.out || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                echo "verrazzano-application-operator logs dumped to oam-kubernetes-runtime-pod.log"
+                echo "verrazzano-application-operator pod description dumped to oam-kubernetes-runtime-pod.out"
+                echo "------------------------------------------"
+            """
+        }
+    }
 }
 
-def dumpVerrazzanoApiLogs(count) {
-    sh """
-        export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
-        LOG_DIR="${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/cluster-$count"
-        mkdir -p ${LOG_DIR}
-        export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-api.log"
-        ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -r "verrazzano-api-*" -m "verrazzano api" -l || echo "failed" > ${POST_DUMP_FAILED_FILE}
-    """
+def dumpVerrazzanoApiLogs() {
+    script {
+        int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+        for(int count=1; count<=clusterCount; count++) {
+            sh """
+                export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
+                LOG_DIR="${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/cluster-$count"
+                mkdir -p ${LOG_DIR}
+                export DIAGNOSTIC_LOG="${LOG_DIR}/verrazzano-api.log"
+                ${GO_REPO_PATH}/verrazzano/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -r "verrazzano-api-*" -m "verrazzano api" -l || echo "failed" > ${POST_DUMP_FAILED_FILE}
+            """
+        }
+    }
 }
