Revert multicluster Jenkinsfile changes

diff --git a/ci/multicluster/Jenkinsfile b/ci/multicluster/Jenkinsfile
--- a/ci/multicluster/Jenkinsfile
+++ b/ci/multicluster/Jenkinsfile
@@ -37,10 +37,6 @@ pipeline {
         choice (description: 'Number of Cluster', name: 'TOTAL_CLUSTERS', choices: ["2", "1", "3"])
         choice (description: 'Verrazzano Test Environment', name: 'TEST_ENV',
                 choices: ["KIND", "magicdns_oke", "ocidns_oke"])
-        choice (description: 'Update Wildcard DNS to OCI DNS\n Works only if Wildcard DNS is selected, i.e. TEST_ENV != ocidns_oke', name: 'UPDATE_DNS_TO_OCI',
-                choices: ["yes", "no"])
-        choice (description: 'Private zone works only in case of OKE clusters, i.e. TEST_ENV != KIND', name: 'OCI_DNS_TYPE',
-                choices: ["public", "private"])
         choice (description: 'ACME Certificate Environment (Staging or Production)', name: 'ACME_ENVIRONMENT',
                 choices: acmeEnvironments)
         choice (description: 'OCI region to launch OKE clusters', name: 'OKE_CLUSTER_REGION',
@@ -206,48 +202,79 @@ pipeline {
 
     stages {
         stage('Clean workspace and checkout') {
-           steps {
-               cleanWorkspaceAndCheckout()
-           } 
-        }
-        
-        stage("Setup OCI DNS") {
-            when { expression { return params.TEST_ENV == 'ocidns_oke' || params.UPDATE_DNS_TO_OCI == 'yes'} }
-            stages {
-                stage ("Create OCI DNS Zone") {
-                    parallel {
-                        stage('Create OCI public DNS zone') {
-                            when { expression { return params.OCI_DNS_TYPE == 'public' } } 
-                            steps {
-                                script {
-                                    sh """
-                                    echo $OCI_CLI_TENANCY -- $OCI_CLI_USER -- $OCI_CLI_FINGERPRINT -- $OCI_CLI_KEY_FILE -- $OCI_CLI_REGION -- z$zoneId
-                                    oci dns zone list --compartment-id $TF_VAR_compartment_id
-                                    """
-                                    dns_zone_ocid = sh(script: "${GO_REPO_PATH}/verrazzano/tests/e2e/config/scripts/oci_dns_ops.sh -o create -c ${TF_VAR_compartment_id} -s z${zoneId} -k GLOBAL", returnStdout: true)
-                                }
-                            }
-                        }
-                        stage('Create OCI private DNS zone') {
-                            when { expression { return params.OCI_DNS_TYPE == 'private' } } 
-                            steps {
-                                script {
-                                    // TODO: Supply the private view ID
-                                    dns_zone_ocid = sh(script: "${GO_REPO_PATH}/verrazzano/tests/e2e/config/scripts/oci_dns_ops.sh -o create -c ${TF_VAR_compartment_id} -s z${zoneId} -k PRIVATE", returnStdout: true)
-                                }
-                            }
+            steps {
+                sh """
+                    echo "${NODE_LABELS}"
+                """
+
+                script {
+                    EFFECTIVE_DUMP_K8S_CLUSTER_ON_SUCCESS = getEffectiveDumpOnSuccess()
+                    if (params.GIT_COMMIT_TO_USE == "NONE") {
+                        echo "Specific GIT commit was not specified, use current head"
+                        def scmInfo = checkout scm
+                        env.GIT_COMMIT = scmInfo.GIT_COMMIT
+                        env.GIT_BRANCH = scmInfo.GIT_BRANCH
+                    } else {
+                        echo "SCM checkout of ${params.GIT_COMMIT_TO_USE}"
+                        def scmInfo = checkout([
+                            $class: 'GitSCM',
+                            branches: [[name: params.GIT_COMMIT_TO_USE]],
+                            doGenerateSubmoduleConfigurations: false,
+                            extensions: [],
+                            submoduleCfg: [],
+                            userRemoteConfigs: [[url: env.SCM_VERRAZZANO_GIT_URL]]])
+                        env.GIT_COMMIT = scmInfo.GIT_COMMIT
+                        env.GIT_BRANCH = scmInfo.GIT_BRANCH
+                        // If the commit we were handed is not what the SCM says we are using, fail
+                        if (!env.GIT_COMMIT.equals(params.GIT_COMMIT_TO_USE)) {
+                            echo "SCM didn't checkout the commit we expected. Expected: ${params.GIT_COMMIT_TO_USE}, Found: ${scmInfo.GIT_COMMIT}"
+                            exit 1
                         }
                     }
+                    echo "SCM checkout of ${env.GIT_BRANCH} at ${env.GIT_COMMIT}"
                 }
-                stage('Configure OCI DNS Resources') {
-                    environment {
-                        OCI_DNS_COMPARTMENT_OCID = credentials('oci-dns-compartment')
-                        OCI_PRIVATE_KEY_FILE = credentials('oci-api-key')
-                        OCI_DNS_ZONE_OCID = "${dns_zone_ocid}"
+
+                sh """
+                    cp -f "${NETRC_FILE}" $HOME/.netrc
+                    chmod 600 $HOME/.netrc
+                """
+
+                script {
+                    try {
+                        sh """
+                            echo "${DOCKER_CREDS_PSW}" | docker login ${env.DOCKER_REPO} -u ${DOCKER_CREDS_USR} --password-stdin
+                        """
+                    } catch(error) {
+                        echo "docker login failed, retrying after sleep"
+                        retry(4) {
+                            sleep(30)
+                            sh """
+                                echo "${DOCKER_CREDS_PSW}" | docker login ${env.DOCKER_REPO} -u ${DOCKER_CREDS_USR} --password-stdin
+                            """
+                        }
                     }
-                    steps {
-                        configureOCIDNSResources()
+	            }
+                sh """
+                    rm -rf ${GO_REPO_PATH}/verrazzano
+                    mkdir -p ${GO_REPO_PATH}/verrazzano
+                    tar cf - . | (cd ${GO_REPO_PATH}/verrazzano/ ; tar xf -)
+                """
+                script {
+                    def props = readProperties file: '.verrazzano-development-version'
+                    VERRAZZANO_DEV_VERSION = props['verrazzano-development-version']
+                    TIMESTAMP = sh(returnStdout: true, script: "date +%Y%m%d%H%M%S").trim()
+                    SHORT_COMMIT_HASH = sh(returnStdout: true, script: "git rev-parse --short=8 HEAD").trim()
+                    DOCKER_IMAGE_TAG = "${VERRAZZANO_DEV_VERSION}-${TIMESTAMP}-${SHORT_COMMIT_HASH}"
+                    // update the description with some meaningful info
+                    setDisplayName()
+                    currentBuild.description = SHORT_COMMIT_HASH + " : " + env.GIT_COMMIT + " : " + params.GIT_COMMIT_TO_USE
+
+                    if (params.TEST_ENV != "KIND") {
+                        // derive the prefix for the OKE cluster
+                        OKE_CLUSTER_PREFIX = sh(returnStdout: true, script: "${GO_REPO_PATH}/verrazzano/ci/scripts/derive_oke_cluster_name.sh").trim()
                     }
+                    // Derive Kubernetes version, which is used to set the value for a label in the metrics emitted by the tests
+                    env.K8S_VERSION_LABEL = "${params.TEST_ENV == 'KIND' ? params.KIND_CLUSTER_VERSION : sh(returnStdout: true, script: "${WORKSPACE}/ci/scripts/derive_kubernetes_version.sh ${params.OKE_CLUSTER_VERSION}").trim()}"
                 }
             }
         }
@@ -282,16 +309,46 @@ pipeline {
                 }
                 stage("Configure Clusters") {
                     parallel {
-                        stage('Configure OKE/OCI DNS') {
+                        stage("Configure OKE/OCI DNS") {
                             when { expression { return params.TEST_ENV == 'ocidns_oke' } }
-                            environment {
-                                OCI_DNS_COMPARTMENT_OCID = credentials('oci-dns-compartment')
-                                OCI_PRIVATE_KEY_FILE = credentials('oci-api-key')
-                                OCI_DNS_ZONE_OCID = "${dns_zone_ocid}"
-                            }
-                            steps {
-                                script {
-                                    configureVerrazzanoInstallers(env.INSTALL_CONFIG_FILE_OCIDNS, "./tests/e2e/config/scripts/process_oci_dns_install_yaml.sh", "acme", params.ACME_ENVIRONMENT)
+                            stages {
+                                stage('Create OCI DNS zone') {
+                                    steps {
+                                        script {
+                                            dns_zone_ocid = sh(script: "${GO_REPO_PATH}/verrazzano/tests/e2e/config/scripts/oci_dns_ops.sh -o create -c ${TF_VAR_compartment_id} -s z${zoneId}", returnStdout: true)
+                                        }
+                                    }
+                                }
+                                stage('Configure OCI DNS Resources') {
+                                    environment {
+                                        OCI_DNS_COMPARTMENT_OCID = credentials('oci-dns-compartment')
+                                        OCI_PRIVATE_KEY_FILE = credentials('oci-api-key')
+                                        OCI_DNS_ZONE_OCID = "${dns_zone_ocid}"
+                                    }
+                                    steps {
+                                        script {
+                                            int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+                                            for(int count=1; count<=clusterCount; count++) {
+                                                sh """
+                                                    export KUBECONFIG=${KUBECONFIG_DIR}/$count/kube_config
+                                                    cd ${GO_REPO_PATH}/verrazzano
+                                                    ./tests/e2e/config/scripts/create-test-oci-config-secret.sh
+                                                """
+                                            }
+                                        }
+                                    }
+                                }
+                                stage('Configure OCI DNS Installers') {
+                                    environment {
+                                        OCI_DNS_COMPARTMENT_OCID = credentials('oci-dns-compartment')
+                                        OCI_PRIVATE_KEY_FILE = credentials('oci-api-key')
+                                        OCI_DNS_ZONE_OCID = "${dns_zone_ocid}"
+                                    }
+                                    steps {
+                                        script {
+                                            configureVerrazzanoInstallers(env.INSTALL_CONFIG_FILE_OCIDNS, "./tests/e2e/config/scripts/process_oci_dns_install_yaml.sh", "acme", params.ACME_ENVIRONMENT)
+                                        }
+                                    }
                                 }
                             }
                         }
@@ -387,21 +444,9 @@ pipeline {
 
         stage('Verify Upgrade') {
             // Rerun some stages to verify the upgrade
-            parallel {
-                stage ('Verify Register') {
-                    steps {
-                        verifyRegisterManagedClusters()
-                    }
-                }
-                stage ('Verify Managed Cluster Permissions') {
-                    steps {
-                        verifyManagedClusterPermissions()
-                    }
-                }
-                stage ('Verify Metrics') {
-                    steps {
-                        runGinkgoRandomize('metrics/syscomponents')
-                    }
+            steps {
+                script {
+                    parallel verifyUpgrade()
                 }
             }
             post {
@@ -627,7 +672,95 @@ pipeline {
         }
         always {
             script {
-                runPostPipelineFailureScript()
+                if ( fileExists(env.TESTS_EXECUTED_FILE) ) {
+                    dumpVerrazzanoSystemPods()
+                    dumpCattleSystemPods()
+                    dumpNginxIngressControllerLogs()
+                    dumpVerrazzanoPlatformOperatorLogs()
+                    dumpVerrazzanoApplicationOperatorLogs()
+                    dumpOamKubernetesRuntimeLogs()
+                    dumpVerrazzanoApiLogs()
+                }
+                dumpUninstallLogs()
+            }
+            sh """
+                # Copy the generated test reports to WORKSPACE to archive them
+                mkdir -p ${TEST_REPORT_DIR}
+                cd ${GO_REPO_PATH}/verrazzano/tests/e2e
+                find . -name "${TEST_REPORT}" | cpio -pdm ${TEST_REPORT_DIR}
+            """
+            archiveArtifacts artifacts: "**/*-operator.yaml,**/install-verrazzano.yaml,**/kube_config,**/coverage.html,**/logs/**,**/build/resources/**,**/verrazzano_images.txt,**/*-cluster-dump*/**,**/test-cluster-dumps/**,**/${TEST_REPORT}", allowEmptyArchive: true
+            junit testResults: "**/${TEST_REPORT}", allowEmptyResults: true
+
+            script {
+                 // Create a dictionary of Verrazzano uninstall steps to be executed in parallel
+                 // - the first one will always be the Admin cluster
+                 // - clusters 2-max are managed clusters
+                 def verrazzanoUninstallStages = [:]
+                 int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+                 for (int count = 1; count <= clusterCount; count++) {
+                     def installerPath = "${KUBECONFIG_DIR}/${count}/${installerFileName}"
+                     def key = "vz-mgd-${count - 1}"
+                     if (count == 1) {
+                         key = "vz-admin"
+                     }
+                     verrazzanoUninstallStages["${key}"] = uninstallVerrazzano(count, installerPath)
+                 }
+                 parallel verrazzanoUninstallStages
+            }
+
+            script {
+                // Create a dictionary of Verrazzano verify uninstall steps to be executed in parallel
+                // - the first one will always be the Admin cluster
+                // - clusters 2-max are managed clusters
+                def verifyUninstallStages = [:]
+                int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+                for (int count = 1; count <= clusterCount; count++) {
+                    def key = "vz-mgd-${count - 1}"
+                    if (count == 1) {
+                        key = "vz-admin"
+                    }
+                    verifyUninstallStages["${key}"] = verifyUninstall(count)
+                }
+                parallel verifyUninstallStages
+            }
+
+            script {
+                if (params.EMIT_METRICS) {
+                    withCredentials([usernameColonPassword(credentialsId: 'prometheus-credentials', variable: 'PROMETHEUS_CREDENTIALS')]) {
+                        sh """
+                            ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e" "${PROMETHEUS_CREDENTIALS}" || echo "Emit metrics failed, continuing with other post actions"
+                        """
+                    }
+                }
+
+                int clusterCount = params.TOTAL_CLUSTERS.toInteger()
+                if (env.TEST_ENV == "KIND") {
+                    for(int count=1; count<=clusterCount; count++) {
+                        sh """
+                            if [ "${env.TEST_ENV}" == "KIND" ]
+                            then
+                                kind delete cluster --name ${CLUSTER_NAME_PREFIX}-$count
+                            fi
+                        """
+                    }
+                } else {
+                    sh """
+                        mkdir -p ${KUBECONFIG_DIR}
+                        if [ "${TEST_ENV}" == "ocidns_oke" ]; then
+                          cd ${GO_REPO_PATH}/verrazzano
+                          ./tests/e2e/config/scripts/oci_dns_ops.sh -o delete -s z${zoneId} || echo "Failed to delete DNS zone z${zoneId}"
+                        fi
+                        cd ${TEST_SCRIPTS_DIR}
+                        TF_VAR_label_prefix=${OKE_CLUSTER_PREFIX} TF_VAR_state_name=multicluster-${env.BUILD_NUMBER}-${env.BRANCH_NAME} ./delete_oke_cluster.sh "$clusterCount" "${KUBECONFIG_DIR}" || true
+                    """
+                }
+                sh """
+                    if [ -f ${POST_DUMP_FAILED_FILE} ]; then
+                        echo "Failures seen during dumping of artifacts, treat post as failed"
+                        exit 1
+                    fi
+                """
             }
         }
         cleanup {
@@ -1465,6 +1598,7 @@ def verifyUpgrade() {
     ]
 }
 
+<<<<<<< HEAD
 def cleanWorkspaceAndCheckout() {
     sh """
         echo "${NODE_LABELS}"
@@ -1640,4 +1774,18 @@ def runPostPipelineFailureScript() {
             fi
         """
     }
+}
+
+def verifyUpgrade() {
+    return [
+        "Verify Register": {
+            verifyRegisterManagedClusters()
+        },
+        "Verify Managed Cluster Permissions": {
+            verifyManagedClusterPermissions()
+        },
+        "Verify Metrics": {
+            runGinkgoRandomize('metrics/syscomponents')
+        },
+    ]
 }
