VZ-5624: Add oke stage

diff --git a/ci/backup/Jenkinsfile b/ci/backup/Jenkinsfile
--- a/ci/backup/Jenkinsfile
+++ b/ci/backup/Jenkinsfile
@@ -211,6 +211,40 @@ pipeline {
         }
 
         stage('Backup Acceptance Tests') {
+            stage("install-oke") {
+                when { expression { return params.TEST_ENV != 'kind' } }
+                environment {
+                    TF_VAR_label_prefix="${OKE_CLUSTER_PREFIX}"
+                }
+                steps {
+                    script {
+                        withCredentials([sshUserPrivateKey(credentialsId: '5fcc03de-31ce-4566-b11f-9de38e5d98fd', keyFileVariable: 'OPC_USER_KEY_FILE', passphraseVariable: 'OPC_USER_PASSPHRASE', usernameVariable: 'OPC_USERNAME')]) {
+                        def RUNNER_REGION = sh(returnStdout: true, script: "curl -s -H \"Authorization: Bearer Oracle\" http://169.254.169.254/opc/v2/instance/canonicalRegionName").trim()
+                        env.TF_VAR_region = "${params.DNS_SCOPE == 'PRIVATE' ? RUNNER_REGION : params.OKE_CLUSTER_REGION}"
+                        env.OCI_CLI_REGION = "${params.DNS_SCOPE == 'PRIVATE' ? RUNNER_REGION : params.OKE_CLUSTER_REGION}"
+                        println("runner region is ${RUNNER_REGION}, tf var region is ${env.TF_VAR_REGION}")
+                            sh """
+                                # get the ssh public key
+                                ssh-keygen -y -e -f ${OPC_USER_KEY_FILE} > /tmp/opc_ssh2.pub
+                                # convert SSH2 public key into an OpenSSH format
+                                ssh-keygen -i -f /tmp/opc_ssh2.pub > /tmp/opc_ssh.pub
+                                # set the ssh public key value for terraform
+                                export TF_VAR_ssh_public_key_path=/tmp/opc_ssh.pub
+                                export TF_VAR_state_name=${env.BUILD_NUMBER}-${env.TIMESTAMP}-${env.BRANCH_NAME}
+                                # call create_oke_cluster with cluster access private
+                                ${WORKSPACE}/tests/e2e/config/scripts/create_oke_cluster.sh true ${params.CREATE_CLUSTER_USE_CALICO}
+                            """
+                        }
+                    }
+                }
+                post {
+                    failure {
+                        script {
+                            echo "Cluster create failed"
+                        }
+                    }
+                }
+            }
             stages {
                 stage('Prepare AT environment') {
                    environment {
@@ -266,6 +300,9 @@ pipeline {
                         }
                     }
                     post {
+                        failure {
+
+                         }
                         always {
                             script {
                                  sh """
@@ -495,11 +532,15 @@ def getEffectiveDumpOnSuccess() {
 
 def deleteCluster() {
     sh """
-        cd ${GO_REPO_PATH}/verrazzano/platform-operator
-        make delete-cluster
+        if [ "${TEST_ENV}" == "kind" ]; then
+          cd ${GO_REPO_PATH}/verrazzano/platform-operator
+          make delete-cluster
+        elif [ "${keepOKEClusterOnFailure}" == "false" ]; then
+          TF_VAR_label_prefix=${OKE_CLUSTER_PREFIX} TF_VAR_state_name=${env.BUILD_NUMBER}-${env.TIMESTAMP}-${env.BRANCH_NAME} ${WORKSPACE}/tests/e2e/config/scripts/delete_oke_cluster.sh || true
+        fi
         if [ -f ${POST_DUMP_FAILED_FILE} ]; then
-          echo "Failures seen during dumping of artifacts, treat post as failed"
-          exit 1
+            echo "Failures seen during dumping of artifacts, treat post as failed"
+            exit 1
         fi
     """
 }
