check for namespace existence

diff --git a/ci/uninstall/JenkinsfileUninstallTest b/ci/uninstall/JenkinsfileUninstallTest
--- a/ci/uninstall/JenkinsfileUninstallTest
+++ b/ci/uninstall/JenkinsfileUninstallTest
@@ -485,11 +485,14 @@ def kill_vpo_loop(vpoLogsDir) {
             VZ_STATUS=\$(kubectl get vz my-verrazzano --ignore-not-found -o jsonpath={.status.conditions[-1].type})
             RESTARTS=1
             while [ ! -z \$VZ_STATUS ] && [ \$VZ_STATUS == "UninstallStarted" ] ; do
-                mkdir -p ${WORKSPACE}/verrazzano-platform-operator/logs
-                kubectl -n verrazzano-install logs --tail -1 --selector=app=verrazzano-platform-operator >> ${vpoLogsDir}/verrazzano-platform-operator-before-vpo-killed-pod-\${RESTARTS}.log || echo "failed" > ${POST_DUMP_FAILED_FILE}
-                kubectl -n verrazzano-install delete pod -l app=verrazzano-platform-operator --ignore-not-found
-                kubectl -n verrazzano-install rollout status deployments/verrazzano-platform-operator --timeout=600s
-                echo "VPO pod successfully restarted"
+                NS_STATUS=\$(kubectl get ns verrazzano-install --ignore-not-found -o jsonpath={.status.phase})
+                if [ ! -z "$NS_STATUS" ]; then
+                    mkdir -p ${WORKSPACE}/verrazzano-platform-operator/logs
+                    kubectl -n verrazzano-install logs --tail -1 --selector=app=verrazzano-platform-operator >> ${vpoLogsDir}/verrazzano-platform-operator-before-vpo-killed-pod-\${RESTARTS}.log || echo "failed" > ${POST_DUMP_FAILED_FILE}
+                    kubectl -n verrazzano-install delete pod -l app=verrazzano-platform-operator --ignore-not-found
+                    kubectl -n verrazzano-install rollout status deployments/verrazzano-platform-operator --timeout=600ss
+                    echo "VPO pod successfully restarted"
+                fi
 
                 # Sleep a random interval between 15 and 60 seconds
                 SLEEP_SEC=\$[ \$RANDOM % 45 + 15 ]
