Restore uninstall chaos test

diff --git a/ci/uninstall/JenkinsfileUninstallTest b/ci/uninstall/JenkinsfileUninstallTest
--- a/ci/uninstall/JenkinsfileUninstallTest
+++ b/ci/uninstall/JenkinsfileUninstallTest
@@ -456,13 +456,11 @@ def getUninstallStages(vpoLogsDir) {
              },
     ]
     if (params.CHAOS_TEST_TYPE == "uninstall.interrupt.uninstall") {
-    /* Uncomment this after fixing the issue with verrazzano-install namespace getting removed before vz is uninstalled
         stages = stages + [
              "uninstall-chaos": {
                     kill_vpo_loop(vpoLogsDir)
                  },
         ]
-   */
     }
     return stages
 }
@@ -472,9 +470,24 @@ def uninstallVerrazzano(vpoLogsDir) {
         echo "Platform operator uninstall logs dir: ${vpoLogsDir}"
 
         // Delete VZ in the background
+        // - does not use the CLI as the CLI will also delete the VPO namespace, and until recently the CLI
+        //   was not able to resume an uninstall on error
         sh """
-            echo "Deleting the Verrazzano resource..."
-            ${GO_REPO_PATH}/vz uninstall --timeout=20m 
+            kubectl delete --wait=true --timeout=20m verrazzano my-verrazzano
+
+            #if kubectl get verrazzano my-verrazzano 2>&1 > /dev/null; then
+            #  echo "Waiting for Verrazzano resource to be deleted..."
+            #  kubectl wait verrazzano my-verrazzano --for=delete --timeout=20m
+            #else
+            #  echo "Verrazzano resource my-verrazzano successfully deleted"
+            #fi
+
+            # Wait a bit before continuing
+            sleep 90s
+            kubectl -n verrazzano-install logs --tail -1 --selector=app=verrazzano-platform-operator > ${vpoLogsDir}/verrazzano-platform-operator-post-uninstall.log || echo "failed" > ${POST_DUMP_FAILED_FILE}
+
+            echo "Deleting the Platform Operator resources"
+            kubectl delete -f ${TARGET_OPERATOR_FILE} --wait=true --timeout=10m
         """
     }
 }
