refactoring

diff --git a/ci/cron/JenkinsfileBackend b/ci/cron/JenkinsfileBackend
--- a/ci/cron/JenkinsfileBackend
+++ b/ci/cron/JenkinsfileBackend
@@ -1,31 +1,155 @@
 // Copyright (c) 2023, Oracle and/or its affiliates.
 // Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
 
+import groovy.transform.Field
+
+@Field
+def LAST_BACKEND_COMMIT = ""
+
+def agentLabel = env.JOB_NAME.contains('master') ? "phx-small" : "small"
+
 // Non Fields
 def branchSpecificSchedule = getCronSchedule()
 
-def ociOsRegion = "us-phoenix-1"
-def ociOsBucket = "verrazzano-builds"
-def urlTriggerBranchName = env.BRANCH_NAME.replace('/', '%2F')
-def CLEAN_BACKEND_OS_LOCATION = "${CLEAN_BRANCH_NAME}-last-clean-backend-test/verrazzano_backend-commit.txt"
+pipeline {
+    options {
+        timeout(time: 12, unit: 'HOURS')
+        skipDefaultCheckout true
+        disableConcurrentBuilds()
+        timestamps ()
+    }
 
-For each branch (master + release-*) {
-    Check if there is anything in objectstore for each branch {
-        If yes, check state {
-            If state changed, kick off new jobs {
-                commit = get(https://objectstorage.us-phoenix-1.oraclecloud.com/n/stevengreenberginc/b/verrazzano-builds/o/master/last-stable-commit.txt)
-                if state.lastBackend != commit {
-                    (run backend pipeline with new commit)
-                    state.lastBackend = commit
-                }
-            }
-            If no change, ignore/continue
-        }
-        If no, kick off new jobs (first time seeing new url/pipeline) {
-            (run periodics pipeline with new commit)
-            state.lastBackend = commit
-            (run backend pipeline with new commit)
-            state.lastBackend = commit
+    agent {
+       docker {
+            image "${RUNNER_DOCKER_IMAGE}"
+            args "${RUNNER_DOCKER_ARGS}"
+            registryUrl "${RUNNER_DOCKER_REGISTRY_URL}"
+            registryCredentialsId 'ocir-pull-and-push-account'
+            label "${agentLabel}"
         }
     }
+
+    triggers {
+        cron(branchSpecificSchedule)
+    }
+
+    parameters {
+            booleanParam (description: 'Skip test execution (for debugging)', name: 'DRY_RUN', defaultValue: false)
+        }
+
+    environment {
+        OCI_CLI_AUTH="instance_principal"
+        OCI_OS_NAMESPACE = credentials('oci-os-namespace')
+
+        OCI_OS_BUCKET="verrazzano-builds"
+        OCI_OS_COMMIT_BUCKET="verrazzano-builds-by-commit"
+        CLEAN_BRANCH_NAME = "${env.BRANCH_NAME.replace("/", "%2F")}"
+
+        LAST_BACKEND_OS_LOCATION = "${CLEAN_BRANCH_NAME}/last-backend-run-commit.txt"
+        LAST_BACKEND_LOCATION = "${WORKSPACE}/last-backend-run-commit.txt"
+
+        OCI_OS_REGION="us-phoenix-1"
+    }
+
+    stages {
+        stage('Clean workspace and checkout') {
+                steps {
+                    script {
+                        cleanWorkspaceAndCheckout()
+                    }
+                }
+        }
+
+        stage('Get most recent backend commit') {
+            steps {
+                getLastBackendRunCommit()
+                echo("Last backend commit: ${LAST_BACKEND_COMMIT}")
+            }
+        }
+
+        stage ('Run Backend Test Suite') {
+            when {
+                allOf {
+                    expression { return runPipeline() }
+                    expression { !params.DRY_RUN }
+                }
+            }
+
+            steps {
+                script {
+                    echo("Running backend suite with commit ${SHORT_COMMIT_HASH}")
+                    build job: "/verrazzano-backend-tests/${CLEAN_BRANCH_NAME}", wait: true
+                }
+            }
+        }
+    }
+}
+
+def cleanWorkspaceAndCheckout() {
+    scmCheckout()
+    def props = readProperties file: '.verrazzano-development-version'
+    VERRAZZANO_DEV_VERSION = props['verrazzano-development-version']
+    TIMESTAMP = sh(returnStdout: true, script: "date +%Y%m%d%H%M%S").trim()
+    SHORT_COMMIT_HASH = sh(returnStdout: true, script: "git rev-parse --short=8 HEAD").trim()
+    // update the description with some meaningful info
+    currentBuild.description = SHORT_COMMIT_HASH + " : " + env.GIT_COMMIT
+}
+
+// Returns the last run commit for the backend suite, or null if the commit file does not exist yet.
+// - fails the pipeline if any error other than 404 is returned by the OCI CLI
+def getLastBackendRunCommit() {
+    lastBackendCommitCommandOutput = sh (
+        label: "Get last clean backend suite commit ID",
+        script: "oci --region us-phoenix-1 os object get --namespace ${OCI_OS_NAMESPACE} -bn ${OCI_OS_BUCKET} --name ${LAST_BACKEND_OS_LOCATION} --file ${LAST_BACKEND_LOCATION} 2>&1 || true",
+        returnStdout: true
+        ).trim()
+    echo "command out: ${lastBackendCommitCommandOutput}"
+    if (lastBackendCommitCommandOutput.length() > 0) {
+        // We can get warning messages here as well even when the command succeeded, so be more precise on the checking
+        if (lastBackendCommitCommandOutput =~ /(.*)status(.*)\d{1,4}(.*)/) {
+            // If we think we had a status: NNN, we ignore 404 and fail for others
+            assert lastBackendCommitCommandOutput =~ /(.*)status(.*)404(.*)/ : "An unexpected error occurred getting last backend suite commit from ObjectStore: ${lastBackendCommitCommandOutput}"
+        } else {
+            // If we got here, we have some message that may or may not be an error. If we don't see the file, we assume it was an error
+            sh """
+                if [ ! -f ${LAST_BACKEND_LOCATION} ]; then
+                    echo "An unexpected error occurred getting last backend suite run commit from ObjectStore: ${lastBackendCommitCommandOutput}"
+                    exit 1
+                fi
+            """
+        }
+    }
+    // Get the commit ID for the last known clean pass of the backend tests
+    def lastBackendCommitProps = readProperties file: "${LAST_BACKEND_LOCATION}"
+    LAST_BACKEND_COMMIT = lastBackendCommitProps['git-commit']
+}
+
+def scmCheckout() {
+    echo "${NODE_LABELS}"
+    echo "Specific GIT commit was not specified, use current head"
+    def scmInfo = checkout([
+        $class: 'GitSCM',
+        branches: [[name: env.BRANCH_NAME]],
+        doGenerateSubmoduleConfigurations: false,
+        extensions: [],
+        submoduleCfg: [],
+        userRemoteConfigs: [[url: env.SCM_VERRAZZANO_GIT_URL]]])
+    env.GIT_COMMIT = scmInfo.GIT_COMMIT
+    env.GIT_BRANCH = scmInfo.GIT_BRANCH
+    echo "SCM checkout of ${env.GIT_BRANCH} at ${env.GIT_COMMIT}"
+}
+
+// Checks if the commit has changed since last run
+def runPipeline() {
+  return LAST_BACKEND_COMMIT != SHORT_COMMIT_HASH
+}
+
+def getCronSchedule() {
+    if (env.BRANCH_NAME.equals("master")) {
+        // scheduled for every 6 hours
+        return "0 */6 * * *"
+    } else if (env.BRANCH_NAME.startsWith("release-")) {
+        return "0 */6 * * *"
+    }
+    return ""
 }
