install ginkgo version 2.0 before running the tests

diff --git a/platform-operator/Makefile b/platform-operator/Makefile
--- a/platform-operator/Makefile
+++ b/platform-operator/Makefile
@@ -65,6 +65,9 @@ CRD_PATH=helm_config/charts/verrazzano-platform-operator/crds
 
 CLUSTER_DUMP_LOCATION ?= platform-operator-integ-cluster-dump
 
+#update to ginkgo version 2.0
+$(shell go get github.com/onsi/ginkgo/ginkgo@ver2)
+$(shell go install github.com/onsi/ginkgo/ginkgo@ver2)
 
 # Run against the configured Kubernetes cluster in ~/.kube/config
 .PHONY: run
@@ -161,7 +164,7 @@ integ-test: create-cluster generate-operator-yaml
 	echo 'Deploy verrazzano platform operator ...'
 	kubectl apply -f ${OPERATOR_YAML} || (echo 'Platform operator install failed, capturing kind cluster dump'; ../tools/scripts/k8s-dump-cluster.sh -d ${CLUSTER_DUMP_LOCATION} -r ${CLUSTER_DUMP_LOCATION}/analysis.report; exit 1)
 	echo 'Run tests...'
-	ginkgo -v --keepGoing -cover test/integ/... || (echo 'Platform operator tests failed, capturing kind cluster dump'; ../tools/scripts/k8s-dump-cluster.sh -d ${CLUSTER_DUMP_LOCATION} -r ${CLUSTER_DUMP_LOCATION}/analysis.report; exit 1)
+	ginkgo -v --keep-going -cover test/integ/... || (echo 'Platform operator tests failed, capturing kind cluster dump'; ../tools/scripts/k8s-dump-cluster.sh -d ${CLUSTER_DUMP_LOCATION} -r ${CLUSTER_DUMP_LOCATION}/analysis.report; exit 1)
 
 .PHONY: generate-operator-yaml
 generate-operator-yaml:
