Revert the change to Jenkinsfile used by OCI DNS pipeline

diff --git a/ci/oke-ocidns/Jenkinsfile b/ci/oke-ocidns/Jenkinsfile
--- a/ci/oke-ocidns/Jenkinsfile
+++ b/ci/oke-ocidns/Jenkinsfile
@@ -447,152 +447,180 @@ pipeline {
             }
         }
 
-        stage('verify-install') {
-            steps {
-                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
-                    sh """
-                        cd ${WORKSPACE}/tests/e2e
-                        ginkgo -p --randomize-all -v --keep-going --no-color ${GINKGO_REPORT_ARGS} -tags="${params.TAGGED_TESTS}" --focus-file="${params.INCLUDED_TESTS}" --skip-file="${params.EXCLUDED_TESTS}" verify-install/...
-                    """
+        stage('acceptance-tests-1') {
+            stages {
+                stage('verify-install') {
+                    steps {
+                        catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+                            sh """
+                                cd ${WORKSPACE}/tests/e2e
+                                ginkgo -p --randomize-all -v --keep-going --no-color ${GINKGO_REPORT_ARGS} -tags="${params.TAGGED_TESTS}" --focus-file="${params.INCLUDED_TESTS}" --skip-file="${params.EXCLUDED_TESTS}" verify-install/...
+                            """
+                        }
+                    }
+                }
+                stage('springboot') {
+                    parallel {
+                        // Quick fix for Bob's Books test failure that reports "Webpage is NOT Robert's Books Greetings from Verrazzano!"
+                        //     Do not run this in parallel with Bob's Books because both specify a mapping for "/" path.
+                        // Real fix may be to have each app use a different dnsName in the ingress binding section of the binding file
+                        // and put a host header in the corresponding calls to the app.
+                        stage('generic-springboot') {
+                            environment {
+                                DIAGNOSTIC_LOG="${WORKSPACE}/platform-operator/scripts/install/build/logs/generic-springboot-test.log"
+                                DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-springboot"
+                            }
+                            steps {
+                                script {
+                                    runGinkgo('examples/springboot')
+                                }
+                            }
+                            post {
+                                always {
+                                    dumpGenericSpringbootObjects()
+                                    dumpGenericSpringbootLogs()
+                                }
+                            }
+                        }
+                    }
                 }
             }
         }
 
-        stage('acceptance-tests') {
-            parallel {
-                stage('metrics') {
-                    steps {
-                        script {
-                            runGinkgo('metrics/syscomponents')
+        stage('acceptance-tests-2') {
+            stages {
+                stage('run-acceptance-tests') {
+                    parallel {
+                        stage('metrics') {
+                            steps {
+                                script {
+                                    runGinkgo('metrics/syscomponents')
+                                }
+                            }
+                        }
+                        stage('hello-helidon') {
+                            environment {
+                                DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-hello-helidon"
+                            }
+                            steps {
+                                script {
+                                    runGinkgoFailFast('examples/helidon')
+                                }
+                            }
+                        }
+                        stage('restapi') {
+                            steps {
+                                script {
+                                    runGinkgo('verify-infra/restapi')
+                                }
+                            }
+                        }
+                        stage('vmi') {
+                            steps {
+                                script {
+                                    runGinkgo('verify-infra/vmi')
+                                }
+                            }
+                        }
+                        stage('oam') {
+                            steps {
+                                script {
+                                    runGinkgo('verify-infra/oam')
+                                }
+                            }
+                        }
+                        stage('system logging') {
+                            environment {
+                                DUMP_DIRECTORY="${TEST_DUMP_ROOT}/system-logging"
+                            }
+                            steps {
+                                runGinkgo('logging/system')
+                            }
+                        }
+                        stage('lift-and-shift') {
+                            environment {
+                                DIAGNOSTIC_LOG="${WORKSPACE}/platform-operator/scripts/install/build/logs/lift-and-shift-test.log"
+                                DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-lift-and-shift"
+                            }
+                            steps {
+                                script {
+                                    runGinkgoFailFast('examples/todo')
+                                }
+                            }
+                        }
+                        stage('istio authorization policy') {
+                            environment {
+                                DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-istio-auth-policy"
+                            }
+                            steps {
+                                runGinkgo('istio/authz')
+                            }
+                        }
+                        stage('security role based access') {
+                            environment {
+                                DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-rbac"
+                            }
+                            steps {
+                                runGinkgo('security/rbac')
+                            }
+                        }
+                        stage('bobs-books') {
+                            environment {
+                                DIAGNOSTIC_LOG="${WORKSPACE}/platform-operator/scripts/install/build/logs/bobs-book-test.log"
+                                DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-bobs-books-dump"
+                            }
+                            steps {
+                                script {
+                                    runGinkgoFailFast('examples/bobsbooks')
+                                }
+                                sh """
+                                    ${WORKSPACE}/tests/e2e/config/scripts/get_verrazzano_image.sh bob >> ${IMG_LIST_FILE}
+                                    ${WORKSPACE}/tests/e2e/config/scripts/get_verrazzano_image.sh bobby >> ${IMG_LIST_FILE}
+                                    ${WORKSPACE}/tests/e2e/config/scripts/get_verrazzano_image.sh robert >> ${IMG_LIST_FILE}
+                                """
+                            }
+                            post {
+                                always {
+                                    dumpBobObjects()
+                                    dumpBobLogs()
+                                }
+                            }
+                        }
+                        stage('socks') {
+                            environment {
+                                DIAGNOSTIC_LOG="${WORKSPACE}/platform-operator/scripts/install/build/logs/socks-test.log"
+                                DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-socks"
+                            }
+                            steps {
+                                script {
+                                    runGinkgo('examples/socks')
+                                }
+                                sh """
+                                    ${WORKSPACE}/tests/e2e/config/scripts/create_verrazzano_image_list.sh ${IMG_LIST_FILE}
+                                    # make necessary substitutions
+                                    sed -i 's/example-hello-world-helidon/example-helidon-greet-app-v1/' ${IMG_LIST_FILE}
+                                    sed -i 's/example-bobs-books-order-manager/example-bobs-bookstore-order-manager/' ${IMG_LIST_FILE}
+                                """
+                           }
+                           post {
+                              always {
+                                    dumpSockObjects()
+                                    dumpSockLogs()
+                              }
+                           }
+                        }
+                        stage('WebLogic logging') {
+                            environment {
+                                DUMP_DIRECTORY="${TEST_DUMP_ROOT}/weblogic-logging"
+                            }
+                            steps {
+                                script {
+                                    runGinkgoFailFast('logging/weblogic')
+                                }
+                            }
                         }
                     }
-                }
-                stage('hello-helidon') {
-                    environment {
-                        DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-hello-helidon"
-                    }
-                    steps {
-                        script {
-                            runGinkgoFailFast('examples/helidon')
-                        }
-                    }
-                }
-                stage('restapi') {
-                    steps {
-                        script {
-                            runGinkgo('verify-infra/restapi')
-                        }
-                    }
-                }
-                stage('vmi') {
-                    steps {
-                        script {
-                            runGinkgo('verify-infra/vmi')
-                        }
-                    }
-                }
-                stage('oam') {
-                    steps {
-                        script {
-                            runGinkgo('verify-infra/oam')
-                        }
-                    }
-                }
-                stage('system logging') {
-                    environment {
-                        DUMP_DIRECTORY="${TEST_DUMP_ROOT}/system-logging"
-                    }
-                    steps {
-                        runGinkgo('logging/system')
-                    }
-                }
-                stage('istio authorization policy') {
-                    environment {
-                        DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-istio-auth-policy"
-                    }
-                    steps {
-                        runGinkgo('istio/authz')
-                    }
-                }
-                stage('security role based access') {
-                    environment {
-                        DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-rbac"
-                    }
-                    steps {
-                        runGinkgo('security/rbac')
-                    }
-                }
-                // Revisit this
-                stage('bobs-books') {
-                    environment {
-                        DIAGNOSTIC_LOG="${WORKSPACE}/platform-operator/scripts/install/build/logs/bobs-book-test.log"
-                        DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-bobs-books-dump"
-                    }
-                    steps {
-                        script {
-                            runGinkgoFailFast('examples/bobsbooks')
-                        }
-                        sh """
-                            ${WORKSPACE}/tests/e2e/config/scripts/get_verrazzano_image.sh bob >> ${IMG_LIST_FILE}
-                            ${WORKSPACE}/tests/e2e/config/scripts/get_verrazzano_image.sh bobby >> ${IMG_LIST_FILE}
-                            ${WORKSPACE}/tests/e2e/config/scripts/get_verrazzano_image.sh robert >> ${IMG_LIST_FILE}
-                        """
-                    }
-                    post {
-                        always {
-                            dumpBobObjects()
-                            dumpBobLogs()
-                        }
-                    }
-                }
-                stage('socks') {
-                    environment {
-                        DIAGNOSTIC_LOG="${WORKSPACE}/platform-operator/scripts/install/build/logs/socks-test.log"
-                        DUMP_DIRECTORY="${TEST_DUMP_ROOT}/examples-socks"
-                    }
-                    steps {
-                        script {
-                            runGinkgo('examples/socks')
-                        }
-                        sh """
-                            ${WORKSPACE}/tests/e2e/config/scripts/create_verrazzano_image_list.sh ${IMG_LIST_FILE}
-                            # make necessary substitutions
-                            sed -i 's/example-hello-world-helidon/example-helidon-greet-app-v1/' ${IMG_LIST_FILE}
-                            sed -i 's/example-bobs-books-order-manager/example-bobs-bookstore-order-manager/' ${IMG_LIST_FILE}
-                        """
-                   }
-                   post {
-                      always {
-                            dumpSockObjects()
-                            dumpSockLogs()
-                      }
-                   }
-                }
-                stage('WebLogic logging') {
-                    environment {
-                        DUMP_DIRECTORY="${TEST_DUMP_ROOT}/weblogic-logging"
-                    }
-                    steps {
-                        script {
-                            runGinkgoFailFast('logging/weblogic')
-                        }
-                    }
-                }
-                stage('weblogic workload') {
-                    environment {
-                        DUMP_DIRECTORY="${TEST_DUMP_ROOT}/weblogic-workload"
-                    }
-                    steps {
-                        runGinkgoFailFast('workloads/weblogic')
-                    }
-                }
-                stage('coherence workload') {
-                    environment {
-                        DUMP_DIRECTORY="${TEST_DUMP_ROOT}/coherence-workload"
-                    }
-                    steps {
-                        runGinkgoFailFast('workloads/coherence')
-                    }
+
                 }
             }
         }
@@ -749,6 +777,24 @@ def dumpBobLogs() {
         ${WORKSPACE}/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -r "vmi-system-prometheus-gw-*" -m "verrazzano system bobs books binding prometheus-gw log" -l -c prometheus-gw || echo "failed" > ${POST_DUMP_FAILED_FILE}
         export DIAGNOSTIC_LOG="${WORKSPACE}/platform-operator/scripts/install/build/logs/monitoring-prom-pusher-system.log"
         ${WORKSPACE}/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n monitoring -r "prom-pusher-system-*" -m "monitoring prom pusher bobs books binding" -l -c prometheus-pusher || echo "failed" > ${POST_DUMP_FAILED_FILE}
+     """
+}
+
+def dumpGenericSpringbootObjects() {
+    sh """
+        ${WORKSPACE}/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n springboot -r "verrazzano-springboot-*" -m "generic springboot app" || echo "failed" > ${POST_DUMP_FAILED_FILE}
+
+        ${WORKSPACE}/platform-operator/scripts/install/k8s-dump-objects.sh -o nodes -n default -m "describing nodes" || echo "failed" > ${POST_DUMP_FAILED_FILE}
+
+        kubectl get event -A || echo "failed" > ${POST_DUMP_FAILED_FILE}
+    """
+}
+
+def dumpGenericSpringbootLogs() {
+    dumpVerrazzanoApiLogs()
+    sh """
+        export DIAGNOSTIC_LOG="${WORKSPACE}/platform-operator/scripts/install/build/logs/verrazzano-springboot.log"
+        ${WORKSPACE}/platform-operator/scripts/install/k8s-dump-objects.sh -o pods -n springboot -r "verrazzano-springboot-*" -m "verrazzano springboot" -l -c verrazzano-springboot || echo "failed" > ${POST_DUMP_FAILED_FILE}
      """
 }
 
