A different approach

diff --git a/ci/oke-ocidns/Jenkinsfile b/ci/oke-ocidns/Jenkinsfile
--- a/ci/oke-ocidns/Jenkinsfile
+++ b/ci/oke-ocidns/Jenkinsfile
@@ -399,20 +399,18 @@ pipeline {
             steps {
                 sh """
                     echo "Waiting for Operator to be ready"
+                    set -x
                     kubectl -n verrazzano-install rollout status deployment/verrazzano-platform-operator
                     echo "Installing Verrazzano on ${TEST_ENV}"
                     # apply config to create cluster
-                    retval=1
-                    retries=0
-                    while [[ $retval -ne 0 ]] && [[ $retries -lt 10 ]] ; do
-                        if [ "${TEST_ENV}" == "magicdns_oke" ]; then
-                            retval=$("kubectl apply -f ${INSTALL_CONFIG_FILE_NIPIO}")
-                        elif [ "${TEST_ENV}" == "ocidns_oke" ]; then
-                            retval=$("kubectl apply -f ${INSTALL_CONFIG_FILE_OCIDNS}")
-                        elif [ "${TEST_ENV}" == "kind" ]; then
-                            retval=$("kubectl apply -f ${INSTALL_CONFIG_FILE_NODEPORT}")
-                        fi
-                        retries=$((retries+1))
+                    install_retries=0
+                    until kubectl apply -f ${INSTALL_CONFIG_FILE_OCIDNS}; do
+                      install_retries=$((install_retries+1))
+                      sleep 6
+                      if [ $install_retries -ge 10 ] ; then
+                        echo "Installation Failed trying to apply the Verrazzano CR YAML"
+                        exit 1
+                      fi
                     done
                     # wait for Verrazzano install to complete
                     ${WORKSPACE}/tests/e2e/config/scripts/wait-for-verrazzano-install.sh
