Add a script to derive the cluster prefix for OKE

diff --git a/ci/oke-ocidns/Jenkinsfile b/ci/oke-ocidns/Jenkinsfile
--- a/ci/oke-ocidns/Jenkinsfile
+++ b/ci/oke-ocidns/Jenkinsfile
@@ -84,8 +84,6 @@ pipeline {
         POST_DUMP_FAILED = 'false'
         GOPATH = '/home/opc/go'
 
-        TIMESTAMP = sh(returnStdout: true, script: "date +%Y%m%d%H%M%S").trim()
-
         TF_VAR_tenancy_id = credentials('oci-tenancy')
         TF_VAR_user_id = credentials('oci-user-ocid')
         TF_VAR_region = "${params.OKE_CLUSTER_REGION}"
@@ -96,10 +94,6 @@ pipeline {
         TF_VAR_s3_bucket_access_key = credentials('oci-s3-bucket-access-key')
         TF_VAR_s3_bucket_secret_key = credentials('oci-s3-bucket-secret-key')
         TF_VAR_ssh_public_key_path = credentials('oci-tf-pub-ssh-key')
-        TF_VAR_compartment_id = credentials('oci-tiburon-dev-compartment-ocid')
-
-        TF_VAR_label_prefix = "${env.BRANCH_NAME == 'master' ? 'ocidns-master-' + env.BUILD_NUMBER : env.BUILD_NUMBER + '-' + env.TIMESTAMP}"
-        TF_VAR_state_name = "${env.BUILD_NUMBER + '-' + env.TIMESTAMP + '-' + env.BRANCH_NAME}"
 
         OCI_CLI_TENANCY = credentials('oci-tenancy')
         OCI_CLI_USER = credentials('oci-user-ocid')
@@ -112,6 +106,8 @@ pipeline {
         KUBECONFIG = "${WORKSPACE}/test_kubeconfig"
         VERRAZZANO_KUBECONFIG = "${KUBECONFIG}"
 
+        TF_VAR_compartment_id = credentials('oci-tiburon-dev-compartment-ocid')
+
         SOCKS_MODEL_FILE = "${WORKSPACE}/examples/sock-shop/sock-shop-model.yaml"
         SOCKS_BINDING_FILE = "${WORKSPACE}/examples/sock-shop/sock-shop-binding.yaml"
         BOBS_MODEL_FILE = "${WORKSPACE}/examples/bobs-books/bobs-books-model.yaml"
@@ -123,6 +119,8 @@ pipeline {
         DISABLE_SPINNER=1
         OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING = 'True'
 
+        TIMESTAMP = sh(returnStdout: true, script: "date +%Y%m%d%H%M%S").trim()
+        SHORT_TIME_STAMP = sh(returnStdout: true, script: "date +%m%d%H%M").trim()
         GITHUB_API_TOKEN = credentials('github-api-token-release-assets')
 
         IMG_LIST_FILE = "${WORKSPACE}/verrazzano_images.txt"
@@ -141,8 +139,6 @@ pipeline {
         DUMP_KUBECONFIG="${KUBECONFIG}"
         DUMP_COMMAND="${WORKSPACE}/tools/scripts/k8s-dump-cluster.sh"
         TEST_DUMP_ROOT="${WORKSPACE}/test-cluster-dumps"
-
-
     }
 
     stages {
@@ -205,8 +201,17 @@ pipeline {
                             ssh-keygen -i -f /tmp/opc_ssh2.pub > /tmp/opc_ssh.pub
                             # set the ssh public key value for terraform
                             export TF_VAR_ssh_public_key_path=/tmp/opc_ssh.pub
-                            echo "TF_VAR_label_prefix : ${TF_VAR_label_prefix}"
-                            echo "TF_VAR_state_name : ${TF_VAR_state_name}"
+
+                            cd ${WORKSPACE}/ci/scripts
+                            ./derive_oke_cluster_name.sh 1> oke_cluster.log 2> error.txt ; [ -s "error.txt" ] || rm -f "error.txt"
+                            if [ -f error.txt ]; then
+                                echo "Failures seen while deriving the OKE cluster name."
+                                exit 1
+                            fi
+                            TF_VAR_label_prefix=\$(cat ./oke_cluster.log)
+                            echo "TF_VAR_label_prefix \${TF_VAR_label_prefix}"
+                            export TF_VAR_label_prefix
+                            export TF_VAR_state_name=${env.BUILD_NUMBER}-${env.TIMESTAMP}-${env.BRANCH_NAME}
                             # call create_oke_cluster with cluster access private
                             ${WORKSPACE}/tests/e2e/config/scripts/create_oke_cluster.sh true ${params.CREATE_CLUSTER_USE_CALICO}
                         """
@@ -560,7 +565,16 @@ pipeline {
                 if [ "${TEST_ENV}" == "kind" ]; then
                   ${WORKSPACE}/tests/e2e/config/scripts/delete-kind-cluster.sh
                 elif [ "${keepOKEClusterOnFailure}" == "false" ]; then
-                  ${WORKSPACE}/tests/e2e/config/scripts/delete_oke_cluster.sh
+                  cd ${WORKSPACE}/ci/scripts
+                  ./derive_oke_cluster_name.sh 1> oke_cluster.log 2> error.txt ; [ -s "error.txt" ] || rm -f "error.txt"
+                  if [ -f error.txt ]; then
+                    echo "Failures seen while deriving the OKE cluster name."
+                    exit 1
+                  fi
+                  TF_VAR_label_prefix=\$(cat ./oke_cluster.log)
+                  echo "TF_VAR_label_prefix \${TF_VAR_label_prefix}"
+                  export TF_VAR_label_prefix
+                  TF_VAR_state_name=${env.BUILD_NUMBER}-${env.TIMESTAMP}-${env.BRANCH_NAME} ${WORKSPACE}/tests/e2e/config/scripts/delete_oke_cluster.sh
                 fi
                 if [ -f ${POST_DUMP_FAILED_FILE} ]; then
                   echo "Failures seen during dumping of artifacts, treat post as failed"
