Don't fail the Jenkins job if the post action to emit metrics fails (#1485)

diff --git a/ci/kind/Jenkinsfile b/ci/kind/Jenkinsfile
--- a/ci/kind/Jenkinsfile
+++ b/ci/kind/Jenkinsfile
@@ -474,7 +474,7 @@ pipeline {
             junit testResults: '**/*test-result.xml', allowEmptyResults: true
             sh """
                 if [ "${params.EMIT_METRICS}" == "true" ] ; then
-                    ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e"
+                    ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e" || echo "Emit metrics failed, continuing with other post actions"
                 fi
             """
             deleteCluster()
diff --git a/ci/upgrade/Jenkinsfile b/ci/upgrade/Jenkinsfile
--- a/ci/upgrade/Jenkinsfile
+++ b/ci/upgrade/Jenkinsfile
@@ -359,7 +359,7 @@ pipeline {
 
             sh """
                 if [ "${params.EMIT_METRICS}" == "true" ] ; then
-                    ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e"
+                    ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e" || echo "Emit metrics failed, continuing with other post actions"
                 fi
                 cd ${GO_REPO_PATH}/verrazzano/platform-operator
                 make delete-cluster
