VZ-3435, VZ-3646: Align auth proxy kubernetes resource names (#1649)

diff --git a/ci/kind/Jenkinsfile b/ci/kind/Jenkinsfile
--- a/ci/kind/Jenkinsfile
+++ b/ci/kind/Jenkinsfile
@@ -240,9 +240,9 @@ pipeline {
                             script {
                                 if (params.ENABLE_API_ENVOY_LOGGING) {
                                     sh '''
-                                        vz_api_pod=\$(kubectl get pod -n verrazzano-system -l app=verrazzano-api --no-headers -o custom-columns=\":metadata.name\")
+                                        vz_api_pod=\$(kubectl get pod -n verrazzano-system -l app=verrazzano-authproxy --no-headers -o custom-columns=\":metadata.name\")
                                         if [ -z "\$vz_api_pod" ]; then
-                                          echo "Could not find verrazzano-api pod, not enabling debug logging"
+                                          echo "Could not find verrazzano-authproxy pod, not enabling debug logging"
                                         else
                                           kubectl exec \$vz_api_pod -c istio-proxy -n verrazzano-system -- curl -X POST http://localhost:15000/logging?level=debug
                                         fi
@@ -626,8 +626,8 @@ def dumpOamKubernetesRuntimeLogs() {
 def dumpVerrazzanoApiLogs() {
     sh """
         cd ${GO_REPO_PATH}/verrazzano/platform-operator
-        export DIAGNOSTIC_LOG="${VERRAZZANO_INSTALL_LOGS_DIR}/verrazzano-api.log"
-        ./scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -r "verrazzano-api-*" -m "verrazzano api" -c verrazzano-api -l || echo "failed" > ${POST_DUMP_FAILED_FILE}
+        export DIAGNOSTIC_LOG="${VERRAZZANO_INSTALL_LOGS_DIR}/verrazzano-authproxy.log"
+        ./scripts/install/k8s-dump-objects.sh -o pods -n verrazzano-system -r "verrazzano-authproxy-*" -m "verrazzano api" -c verrazzano-authproxy -l || echo "failed" > ${POST_DUMP_FAILED_FILE}
     """
 }
 
