Use currentBuild.duration

diff --git a/ci/kind/Jenkinsfile b/ci/kind/Jenkinsfile
--- a/ci/kind/Jenkinsfile
+++ b/ci/kind/Jenkinsfile
@@ -494,11 +494,13 @@ pipeline {
             }
             archiveArtifacts artifacts: '**/coverage.html,**/logs/**,**/verrazzano_images.txt,**/*-cluster-dump/**', allowEmptyArchive: true
             junit testResults: '**/*test-result.xml', allowEmptyResults: true
-            sh """
-                if [ "${params.EMIT_METRICS}" == "true" ] ; then
-                    ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e" || echo "Emit metrics failed, continuing with other post actions"
-                fi
-            """
+            if (params.EMIT_METRICS) {
+                withCredentials([usernameColonPassword(credentialsId: 'verrazzano-sauron', variable: 'SAURON_CREDENTIALS')]) {
+                    sh """
+                        ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e" "${SAURON_CREDENTIALS}" || echo "Emit metrics failed, continuing with other post actions"
+                    """
+                }
+            }
             deleteCluster()
         }
         failure {
@@ -521,6 +523,7 @@ pipeline {
             }
         }
         cleanup {
+            echo "Duration actual ${currentBuild.duration}"
             metricBuildDuration()
             deleteDir()
         }
@@ -719,7 +722,7 @@ def metricTimerEnd(metricName, status) {
 // Emit the metrics indicating the duration and result of the build
 def metricBuildDuration() {
     def status = "${currentBuild.currentResult}"
-    def duration = "${currentBuild.durationString.replace(' and counting', '')}"
+    def duration = "${currentBuild.duration}"
     testMetric = metricJobName('')
     def metricValue = "0"
     if (status.equals("SUCCESS")) {
diff --git a/ci/oke-ocidns/Jenkinsfile b/ci/oke-ocidns/Jenkinsfile
--- a/ci/oke-ocidns/Jenkinsfile
+++ b/ci/oke-ocidns/Jenkinsfile
@@ -585,10 +585,14 @@ pipeline {
             archiveArtifacts artifacts: '**/coverage.html,**/logs/**,**/verrazzano_images.txt,**/*-cluster-dump/**,**/test-cluster-dumps/**', allowEmptyArchive: true
             junit testResults: '**/*test-result.xml', allowEmptyResults: true
 
+            if (params.EMIT_METRICS) {
+                withCredentials([usernameColonPassword(credentialsId: 'verrazzano-sauron', variable: 'SAURON_CREDENTIALS')]) {
+                    sh """
+                        ${WORKSPACE}/ci/scripts/dashboard/emit_metrics.sh "${WORKSPACE}/tests/e2e" "${SAURON_CREDENTIALS}" || echo "Emit metrics failed, continuing with other post actions"
+                    """
+                }
+            }
             sh """
-                if [ "${params.EMIT_METRICS}" == "true" ] ; then
-                    ${WORKSPACE}/ci/scripts/dashboard/emit_metrics.sh "${WORKSPACE}/tests/e2e" || echo "Emit metrics failed, continuing with other post actions"
-                fi
                 if [ "${TEST_ENV}" == "ocidns_oke" ]; then
                   ${WORKSPACE}/tests/e2e/config/scripts/oci_dns_ops.sh -o delete -s z${zoneId} || echo "Failed to delete DNS zone z${zoneId}"
                 fi
@@ -629,6 +633,10 @@ pipeline {
            }
        }
        cleanup {
+            echo "Duration ${currentBuild.durationString}"
+            echo "Duration actual ${currentBuild.durationString.minus(' and counting')}"
+            echo "Duration actual another ${currentBuild.durationString.replace(' and counting', '')}"
+            echo "Build time trend ${env.BUILD_URL}/job/BranchBuild/buildTimeTrend"
            metricBuildDuration()
            deleteDir()
        }
@@ -885,7 +893,7 @@ def metricTimerEnd(metricName, status) {
 // Emit the metrics indicating the duration and result of the build
 def metricBuildDuration() {
     def status = "${currentBuild.currentResult}"
-    def duration = "${currentBuild.durationString.replace(' and counting', '')}"
+    def duration = "${currentBuild.duration}"
     testMetric = metricJobName('')
     def metricValue = "0"
     if (status.equals("SUCCESS")) {
diff --git a/ci/uninstall/Jenkinsfile b/ci/uninstall/Jenkinsfile
--- a/ci/uninstall/Jenkinsfile
+++ b/ci/uninstall/Jenkinsfile
@@ -505,11 +505,13 @@ pipeline {
         always {
             archiveArtifacts artifacts: '**/oke_kubeconfig,**/coverage.html,**/logs/**,**/build/resources/**,**/verrazzano_images.txt,**/*-cluster-dump/**', allowEmptyArchive: true
             junit testResults: '**/*test-result.xml', allowEmptyResults: true
-            sh """
-                if [ "${params.EMIT_METRICS}" == "true" ] ; then
-                    ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e" || echo "Emit metrics failed, continuing with other post actions"
-                fi
-            """
+            if (params.EMIT_METRICS) {
+                withCredentials([usernameColonPassword(credentialsId: 'verrazzano-sauron', variable: 'SAURON_CREDENTIALS')]) {
+                    sh """
+                        ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e" "${SAURON_CREDENTIALS}" || echo "Emit metrics failed, continuing with other post actions"
+                    """
+                }
+            }
         }
         failure {
             script {
@@ -532,6 +534,11 @@ pipeline {
         }
         cleanup {
             sh "VERRAZZANO_KUBECONFIG=${env.KUBECONFIG} TF_VAR_label_prefix=${OKE_CLUSTER_PREFIX} TF_VAR_state_name=uninstall-${env.BUILD_NUMBER}-${env.BRANCH_NAME}/${env.TIMESTAMP} ${GO_REPO_PATH}/verrazzano/tests/e2e/config/scripts/delete_oke_cluster.sh"
+            echo "Duration ${currentBuild.durationString}"
+            echo "Duration actual ${currentBuild.durationString.minus(' and counting')}"
+            echo "Duration actual another ${currentBuild.durationString.replace(' and counting', '')}"
+            echo "Duration actual ${currentBuild.duration}"
+            echo "Build time trend ${env.BUILD_URL}/job/BranchBuild/buildTimeTrend"
             metricBuildDuration()
             deleteDir()
         }
@@ -701,7 +708,7 @@ def metricTimerEnd(metricName, status) {
 // Emit the metrics indicating the duration and result of the build
 def metricBuildDuration() {
     def status = "${currentBuild.currentResult}"
-    def duration = "${currentBuild.durationString.replace(' and counting', '')}"
+    def duration = "${currentBuild.duration}"
     testMetric = metricJobName('')
     def metricValue = "0"
     if (status.equals("SUCCESS")) {
diff --git a/ci/upgrade/Jenkinsfile b/ci/upgrade/Jenkinsfile
--- a/ci/upgrade/Jenkinsfile
+++ b/ci/upgrade/Jenkinsfile
@@ -367,11 +367,14 @@ pipeline {
             }
             archiveArtifacts artifacts: '**/coverage.html,**/logs/**,**/verrazzano_images.txt,**/*-cluster-dump/**', allowEmptyArchive: true
             junit testResults: '**/*test-result.xml', allowEmptyResults: true
-
+            if (params.EMIT_METRICS) {
+                withCredentials([usernameColonPassword(credentialsId: 'verrazzano-sauron', variable: 'SAURON_CREDENTIALS')]) {
+                    sh """
+                        ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e" "${SAURON_CREDENTIALS}" || echo "Emit metrics failed, continuing with other post actions"
+                    """
+                }
+            }
             sh """
-                if [ "${params.EMIT_METRICS}" == "true" ] ; then
-                    ${GO_REPO_PATH}/verrazzano/ci/scripts/dashboard/emit_metrics.sh "${GO_REPO_PATH}/verrazzano/tests/e2e" || echo "Emit metrics failed, continuing with other post actions"
-                fi
                 cd ${GO_REPO_PATH}/verrazzano/platform-operator
                 make delete-cluster
                 cd ${WORKSPACE}/verrazzano
@@ -543,7 +546,7 @@ def metricTimerEnd(metricName, status) {
 // Emit the metrics indicating the duration and result of the build
 def metricBuildDuration() {
     def status = "${currentBuild.currentResult}"
-    def duration = "${currentBuild.durationString.replace(' and counting', '')}"
+    def duration = "${currentBuild.duration}"
     testMetric = metricJobName('')
     def metricValue = "0"
     if (status.equals("SUCCESS")) {
