JIRA:VZ-4926 Add uninstall during upgrade failure test and fix discovered issue in controller (#2634)
* add uninstall test and handle deletion request during upgrade

diff --git a/ci/chaos/Jenkinsfile b/ci/chaos/Jenkinsfile
--- a/ci/chaos/Jenkinsfile
+++ b/ci/chaos/Jenkinsfile
@@ -33,10 +33,6 @@ pipeline {
                 defaultValue: 'NONE',
                 description: 'This is the full git commit hash for the target upgrade.  By default, the Verrazzano tip will be used.',
                 trim: true)
-        string (name: 'VERRAZZANO_OPERATOR_IMAGE',
-                defaultValue: 'NONE',
-                description: 'Verrazzano platform operator image name (in ghcr.io repo).  If not specified, the operator.yaml from Verrazzano repo will be used to create Verrazzano platform operator',
-                trim: true)
         choice (name: 'WILDCARD_DNS_DOMAIN',
                 description: 'This is the wildcard DNS domain',
                 // 1st choice is the default value
@@ -60,7 +56,7 @@ pipeline {
         choice (name: 'CHAOS_TEST_TYPE',
                 description: 'Type of chaos to inflict',
                 // 1st choice is the default value
-                choices: [ "helm.chart.corrupted", "vpo.killed" ])
+                choices: [ "helm.chart.corrupted", "vpo.killed", "uninstall.failed.upgrade" ])
     }
 
     environment {
@@ -87,11 +83,12 @@ pipeline {
         OCR_REPO = 'container-registry.oracle.com'
         IMAGE_PULL_SECRET = 'verrazzano-container-registry'
         INSTALL_CONFIG_FILE_KIND = "./tests/e2e/config/scripts/install-verrazzano-kind-with-persistence.yaml"
-        INSTALL_PROFILE = "dev"
+        INSTALL_PROFILE = "prod"
         VZ_ENVIRONMENT_NAME = "default"
         TEST_SCRIPTS_DIR = "${GO_REPO_PATH}/verrazzano/tests/e2e/config/scripts"
         LOOPING_TEST_SCRIPTS_DIR = "${TEST_SCRIPTS_DIR}/looping-test"
-        VERRAZZANO_OPERATOR_IMAGE="${params.VERRAZZANO_OPERATOR_IMAGE}"
+        // needed for prepare at shell script
+        VERRAZZANO_OPERATOR_IMAGE="NONE"
 
         WEBLOGIC_PSW = credentials('weblogic-example-domain-password') // Needed by ToDoList example test
         DATABASE_PSW = credentials('todo-mysql-password') // Needed by ToDoList example test
@@ -253,40 +250,9 @@ pipeline {
                         }
                     }
                 }
-
-                stage('Run Acceptance Tests Before Upgrade') {
-                    parallel {
-                        stage('verify-infra restapi') {
-                            steps {
-                                runGinkgoRandomize('verify-infra/restapi')
-                            }
-                        }
-                        stage('verify-infra oam') {
-                            steps {
-                                runGinkgoRandomize('verify-infra/oam')
-                            }
-                        }
-                        stage('verify-infra vmi') {
-                            steps {
-                                runGinkgoRandomize('verify-infra/vmi')
-                            }
-                        }
-                        stage('examples spring') {
-                            steps {
-                                runGinkgoNamespace('examples/springboot', "false", "true", "springboot")
-                            }
-                        }
-                        stage('examples helidon') {
-                            steps {
-                                runGinkgoNamespace('examples/helidon', "false", "true", "hello-helidon")
-                            }
-                        }
-                        // Re-enable this stage when a mechanism is in place to deploy different comp and app yamls based on VZ version
-//                         stage('examples socks') {
-//                             steps {
-//                                 runGinkgoNamespace('examples/socks', "false", "true", "sockshop")
-//                             }
-//                         }
+                stage('examples helidon') {
+                    steps {
+                        runGinkgoNamespace('examples/helidon', "false", "true", "hello-helidon")
                     }
                     post {
                         always {
@@ -352,7 +318,7 @@ pipeline {
             }
         }
 
-        stage("Upgrade Verrazzano") {
+        stage("Upgrade Verrazzano and execute selected test") {
             steps {
                 script {
                     // Download the bom for the target version that we are upgrading to, then extract the version
@@ -416,24 +382,46 @@ pipeline {
                         kubectl -n verrazzano-install exec \$POD -- /bin/bash -c "mv /verrazzano/platform-operator/helm_config/charts/verrazzano/values.yaml.bak /verrazzano/platform-operator/helm_config/charts/verrazzano/values.yaml"
                     fi
 
-                    # wait for the upgrade to complete
-                    kubectl wait --timeout=20m --for=condition=UpgradeComplete verrazzano/my-verrazzano
+                   if [[ "uninstall.failed.upgrade" == ${params.CHAOS_TEST_TYPE} ]]
+                    then
+                        # Move values.yaml so helm install of Verrazzano will fail
+                        POD=\$(kubectl get pod -l app=verrazzano-platform-operator -n verrazzano-install -o jsonpath="{.items[0].metadata.name}")
+                        kubectl -n verrazzano-install exec \$POD -- /bin/bash -c "mv /verrazzano/platform-operator/helm_config/charts/verrazzano/values.yaml /verrazzano/platform-operator/helm_config/charts/verrazzano/values.yaml.bak"
+                        # sleep 5 minutes to let the helm upgrade error manifest
+                        until [ `kubectl logs -l app=verrazzano-platform-operator -n verrazzano-install --tail -1 | grep "Failed running Helm command for release verrazzano" | wc -l` -gt 0 ]
+                        do
+                            echo "Waiting for the error message ..."
+                            sleep 30
+                        done
+                        # Make sure the upgrade is still in progress
+                        vz_status=\$(kubectl get vz -o jsonpath='{.items[0].status.conditions[?(@.type=="UpgradeStarted")].type}')
+                        if [[ \${vz_status} == "UpgradeStarted" ]]; then
+                            # Uninstall VZ
+                            kubectl delete verrazzano my-verrazzano
+                        fi
+                    fi
+
+                    if [[ "uninstall.failed.upgrade" != ${params.CHAOS_TEST_TYPE} ]]
+                    then
+                        # wait for the upgrade to complete
+                        # Turn it off for now, Upgrade Fails
+                        kubectl wait --timeout=20m --for=condition=UpgradeComplete verrazzano/my-verrazzano
 
 
-                    # Dump the resource to debug
-                    kubectl get -o yaml verrazzano/my-verrazzano || true
+                        # Dump the resource to debug
+                        kubectl get -o yaml verrazzano/my-verrazzano || true
 
-                    # ideally we don't need to wait here
-                    sleep 15
-                    echo "helm list : releases across all namespaces, after upgrading Verrazzano installation ..."
-                    helm list -A
+                        # ideally we don't need to wait here
+                        sleep 15
+                        echo "helm list : releases across all namespaces, after upgrading Verrazzano installation ..."
+                        helm list -A
 
-                    # Get the install job(s) and mke sure the it matches pre-install.  If there is more than 1 job or the job changed, then it won't match
-                    kubectl -n verrazzano-install get job -o yaml --selector=job-name=verrazzano-install-my-verrazzano > ${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/verrazzano-post-upgrade-job.out
+                        # Get the install job(s) and mke sure the it matches pre-install.  If there is more than 1 job or the job changed, then it won't match
+                        kubectl -n verrazzano-install get job -o yaml --selector=job-name=verrazzano-install-my-verrazzano > ${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/verrazzano-post-upgrade-job.out
 
-                    echo "Ensuring that the install job(s) in verrazzzano-system are identical pre and post install"
-                    cmp -s ${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/verrazzano-pre-upgrade-job.out ${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/verrazzano-post-upgrade-job.out
-
+                        echo "Ensuring that the install job(s) in verrazzzano-system are identical pre and post install"
+                        cmp -s ${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/verrazzano-pre-upgrade-job.out ${WORKSPACE}/verrazzano/platform-operator/scripts/install/build/logs/verrazzano-post-upgrade-job.out
+                    fi
                 """
             }
             post {
@@ -452,6 +440,9 @@ pipeline {
         }
 
         stage('Post-upgrade Acceptance Tests') {
+            when {
+                expression{params.CHAOS_TEST_TYPE != "uninstall.failed.upgrade"}
+            }
             environment {
                 TEST_ENV = "KIND"
                 SEARCH_HTTP_ENDPOINT = credentials('search-gw-url')
@@ -459,107 +450,39 @@ pipeline {
                 SEARCH_USERNAME = "${PROMETHEUS_CREDENTIALS_USR}"
             }
 
-            stages {
-                stage('verify-install') {
+            parallel {
+                stage('verify-upgrade post-upgrade') {
                     steps {
-                        runGinkgoRandomize('verify-install')
+                        runGinkgoRandomize('upgrade/post-upgrade/verify')
                     }
-                    post {
-                        always {
-                            archiveArtifacts artifacts: '**/coverage.html,**/logs/*,**/test-cluster-dumps/**', allowEmptyArchive: true
-                            junit testResults: '**/*test-result.xml', allowEmptyResults: true
-                        }
-                        failure {
-                            script {
-                                if ( fileExists(env.TESTS_EXECUTED_FILE) ) {
-                                    dumpK8sCluster('post-upgrade-install-cluster-dump')
-                                }
-                            }
+                }
+                stage('examples helidon') {
+                    steps {
+                        runGinkgoNamespace('examples/helidon', "true", "false", "hello-helidon")
+                    }
+                }
+            }
+            post {
+                always {
+                    archiveArtifacts artifacts: '**/coverage.html,**/logs/*', allowEmptyArchive: true
+                    junit testResults: '**/*test-result.xml', allowEmptyResults: true
+                }
+                failure {
+                    script {
+                        if ( fileExists(env.TESTS_EXECUTED_FILE) ) {
+                            dumpK8sCluster('post-upgrade-failure-cluster-dump')
                         }
                     }
                 }
-
-                stage('Run Acceptance Tests After Upgrade') {
-                    parallel {
-                        stage("Validate BOM") {
-                            when {
-                                allOf {
-                                    expression{params.RUN_BOM_VALIDATOR == true}
-                                }
-                            }
-                            environment {
-                                OCI_CLI_AUTH="instance_principal"
-                                OCI_OS_NAMESPACE = credentials('oci-os-namespace')
-                                OCI_OS_BUCKET="verrazzano-builds"
-                            }
-                            steps {
-                                sh """
-                                    oci --region us-phoenix-1 os object get --namespace ${OCI_OS_NAMESPACE} -bn ${OCI_OS_BUCKET} --name ${env.BRANCH_NAME}/${SHORT_COMMIT_HASH}/bom-validator --file ${WORKSPACE}/bom-validator
-                                    chmod +x ${WORKSPACE}/bom-validator
-                                    ${WORKSPACE}/bom-validator
-                                """
-                            }
-                        }
-                        stage('verify-infra restapi') {
-                            steps {
-                                runGinkgoRandomize('verify-infra/restapi')
-                            }
-                        }
-                        stage('verify-infra oam') {
-                            steps {
-                                runGinkgoRandomize('verify-infra/oam')
-                            }
-                        }
-                        stage('verify-infra vmi') {
-                            steps {
-                                runGinkgoRandomize('verify-infra/vmi')
-                            }
-                        }
-                        stage('verify-upgrade post-upgrade') {
-                            steps {
-                                runGinkgoRandomize('upgrade/post-upgrade/verify')
-                            }
-                        }
-                        stage('examples socks') {
-                            steps {
-                                runGinkgoNamespace('examples/socks', "false", "false", "sockshop")
-                            }
-                        }
-                        stage('examples spring') {
-                            steps {
-                                runGinkgoNamespace('examples/springboot', "true", "false", "springboot")
-                            }
-                        }
-                        stage('examples helidon') {
-                            steps {
-                                runGinkgoNamespace('examples/helidon', "true", "false", "hello-helidon")
-                            }
-                        }
-                    }
-                    post {
-                        always {
-                            archiveArtifacts artifacts: '**/coverage.html,**/logs/*', allowEmptyArchive: true
-                            junit testResults: '**/*test-result.xml', allowEmptyResults: true
-                        }
-                        failure {
-                            script {
-                                if ( fileExists(env.TESTS_EXECUTED_FILE) ) {
-                                    dumpK8sCluster('post-upgrade-failure-cluster-dump')
-                                }
-                            }
-                        }
-                        success {
-                            script {
-                                if (params.DUMP_K8S_CLUSTER_ON_SUCCESS == true && fileExists(env.TESTS_EXECUTED_FILE) ) {
-                                    dumpK8sCluster('post-upgrade-success-cluster-dump')
-                                }
-                            }
+                success {
+                    script {
+                        if (params.DUMP_K8S_CLUSTER_ON_SUCCESS == true && fileExists(env.TESTS_EXECUTED_FILE) ) {
+                            dumpK8sCluster('post-upgrade-success-cluster-dump')
                         }
                     }
                 }
             }
         }
-
     }
 
     post {
