add vpo dump prior to final vpo upgrade

diff --git a/ci/chaos/Jenkinsfile b/ci/chaos/Jenkinsfile
--- a/ci/chaos/Jenkinsfile
+++ b/ci/chaos/Jenkinsfile
@@ -428,6 +428,8 @@ pipeline {
                         kubectl apply -f ${WORKSPACE}/verrazzano-interim-cr.yaml
                         # wait for the expected error
                         kubectl wait --timeout=15m --for=condition=UpgradeFailed verrazzano/my-verrazzano
+                        mkdir -p ${WORKSPACE}/verrazzano-platform-operator/logs
+                        kubectl -n verrazzano-install logs --tail -1 --selector=app=verrazzano-platform-operator > ${WORKSPACE}/verrazzano-platform-operator/logs/verrazzano-platform-operator-before-final-upgrade-pod.log || echo "failed" > ${POST_DUMP_FAILED_FILE}
                         # Upgrade to the latest VPO
                         kubectl apply -f ${WORKSPACE}/upgrade-test-operator.yaml
                         # ensure operator pod is up
@@ -455,6 +457,8 @@ pipeline {
                             echo "Waiting for the error message ..."
                             sleep 30
                         done
+                        mkdir -p ${WORKSPACE}/verrazzano-platform-operator/logs
+                        kubectl -n verrazzano-install logs --tail -1 --selector=app=verrazzano-platform-operator > ${WORKSPACE}/verrazzano-platform-operator/logs/verrazzano-platform-operator-before-final-upgrade-pod.log || echo "failed" > ${POST_DUMP_FAILED_FILE}
                         # Make sure the upgrade is still in progress
                         vz_status=\$(kubectl get vz -o jsonpath='{.items[0].status.conditions[?(@.type=="UpgradeStarted")].type}')
                         if [[ \${vz_status} == "UpgradeStarted" ]]
