switch to shell File.exists not allowed

diff --git a/ci/JenkinsfilePeriodicTests b/ci/JenkinsfilePeriodicTests
--- a/ci/JenkinsfilePeriodicTests
+++ b/ci/JenkinsfilePeriodicTests
@@ -682,8 +682,12 @@ def getLastCleanPeriodicCommit() {
             assert lastPeriodicCommitCommandOutput =~ /(.*)status(.*)404(.*)/ : "An unexpected error occurred getting last periodic commit from ObjectStore: ${lastPeriodicCommitCommandOutput}"
         } else {
             // If we got here, we have some message that may or may not be an error. If we don't see the file, we assume it was an error
-            File file = new File("${CLEAN_PERIODIC_LOCATION}")
-            assert file.exists() : "An unexpected error occurred getting last periodic commit from ObjectStore: ${lastPeriodicCommitCommandOutput}"
+            sh """
+                if [ ! -f ${CLEAN_PERIODIC_LOCATION} ]; then
+                    echo "An unexpected error occurred getting last periodic commit from ObjectStore: ${lastPeriodicCommitCommandOutput}"
+                    exit 1
+                fi
+            """
         }
     }
     // Get the commit ID for the last known clean pass of the Periodic tests
