VZ-4044: Add pre-release checking to periodic pipeline to identify releasable candidate commits

diff --git a/ci/JenkinsfilePeriodicTests b/ci/JenkinsfilePeriodicTests
--- a/ci/JenkinsfilePeriodicTests
+++ b/ci/JenkinsfilePeriodicTests
@@ -392,6 +392,28 @@ pipeline {
                         }
                     }
                 }
+                stage('Release Candidate Validation Checks') {
+                    environment {
+                        JIRA_USERNAME = credentials('jira-username')
+                        JIRA_PASSWORD = credentials('jira-password')
+                    }
+                    steps {
+                        script {
+                            sh """
+                                cd ${WORKSPACE}
+                                echo "Performing pre-release validation checks for target version ${VERRAZZANO_DEV_VERSION}"
+                                ./release/scripts/prerelease_validation.sh ${VERRAZZANO_DEV_VERSION}
+                                if [ $? -eq 0 ]; then
+                                    echo "Passed pre-release checks for ${VERRAZZANO_DEV_VERSION}, promoting this to the latest releasable candidate"
+                                    echo "git-commit=${env.GIT_COMMIT}" > $WORKSPACE/last-${VERRAZZANO_DEV_VERSION}-releasable-candidate-commit.txt
+                                    oci --region us-phoenix-1 os object put --force --namespace ${OCI_OS_NAMESPACE} -bn ${OCI_OS_BUCKET} --name ${CLEAN_BRANCH_NAME}/last-${VERRAZZANO_DEV_VERSION}-releasable-candidate-commit.txt --file $WORKSPACE/last-${VERRAZZANO_DEV_VERSION}-releasable-candidate-commit.txt
+                                else
+                                    echo "Failed pre-release checks for ${VERRAZZANO_DEV_VERSION}"
+                                fi
+                            """
+                        }
+                    }
+                }
             }
         }
     }
