tvlatas/VZ 4044 (#2090)

diff --git a/ci/JenkinsfilePeriodicTests b/ci/JenkinsfilePeriodicTests
--- a/ci/JenkinsfilePeriodicTests
+++ b/ci/JenkinsfilePeriodicTests
@@ -2,6 +2,11 @@
 // Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
 
 def GIT_COMMIT_TO_USE
+<<<<<<< HEAD
+=======
+def VERRAZZANO_DEV_VERSION
+
+>>>>>>> d1a4af92c... VZ-4044 (#2090)
 def agentLabel = env.JOB_NAME.contains('master') ? "phxlarge" : "VM.Standard2.8"
 def TESTS_FAILED = false
 def tarfilePrefix="verrazzano_periodic"
@@ -261,10 +266,40 @@ pipeline {
                         }
                     }
                 }
+                stage('Release Candidate Validation Checks') {
+                    environment {
+                        JIRA_USERNAME = credentials('jira-username')
+                        JIRA_PASSWORD = credentials('jira-password')
+                    }
+                    steps {
+                        script {
+                            sh """
+                                set +e
+                                cd ${WORKSPACE}
+                                echo "Performing pre-release validation checks for target version ${VERRAZZANO_DEV_VERSION}"
+                                ./release/scripts/prerelease_validation.sh $VERRAZZANO_DEV_VERSION > $WORKSPACE/prerelease_validation.out
+                                if [ \$? -eq 0 ]; then
+                                    echo "Passed pre-release checks for ${VERRAZZANO_DEV_VERSION}, promoting this to the latest releasable candidate"
+                                    echo "git-commit=${env.GIT_COMMIT}" > $WORKSPACE/last-${VERRAZZANO_DEV_VERSION}-releasable-candidate-commit.txt
+                                    oci --region us-phoenix-1 os object put --force --namespace ${OCI_OS_NAMESPACE} -bn ${OCI_OS_BUCKET} --name ${CLEAN_BRANCH_NAME}/last-$VERRAZZANO_DEV_VERSION-releasable-candidate-commit.txt --file $WORKSPACE/last-${VERRAZZANO_DEV_VERSION}-releasable-candidate-commit.txt
+                                    echo "${env.BUILD_NUMBER} : RELEASE CANDIDATE" > release_status.out
+                                else
+                                    echo "Failed pre-release checks for ${VERRAZZANO_DEV_VERSION}"
+                                    echo "${env.BUILD_NUMBER} : NOT RELEASABLE" > release_status.out
+                                fi
+                                set -e
+                            """
+                            currentBuild.displayName = readFile file: "release_status.out"
+                        }
+                    }
+                }
             }
         }
     }
     post {
+        always {
+            archiveArtifacts artifacts: '**/prerelease_validation.out', allowEmptyArchive: true
+        }
         failure {
             script {
                 if (isAlertingEnabled()) {
