Tvlatas/integ fails (#660)
* Do not ignore failures in platform operator failures, fail immediately

* Also propagate fail for deploy

* TEMPORARY CHANGE. This will force the integ test to fail so we can verify it is handled correctly in Jenkins

* Undo the tweak to force the integ test to fail, jenkins failed as expected so that confirmed the error handling fix

* TEMP tweak to force PO integ test failure to test change to move capture location in Jenkins out of GOPATH

* Revert temp plat operator integ test fail, enable temp app operator integ test fail

* Remove temp code that forced app operator integ test failure for jenkins testing

diff --git a/application-operator/Makefile b/application-operator/Makefile
--- a/application-operator/Makefile
+++ b/application-operator/Makefile
@@ -42,6 +42,12 @@ GO ?= CGO_ENABLED=0 GO111MODULE=on GOPRIVATE=github.com/verrazzano go
 GO_LDFLAGS ?= -extldflags -static -X main.buildVersion=${BUILDVERSION} -X main.buildDate=${BUILDDATE}
 CRD_PATH=config/crd/bases
 
+ifdef JENKINS_URL
+	CLUSTER_DUMP_LOCATION = ${WORKSPACE}/application-operator-integ-cluster-dump
+else
+	CLUSTER_DUMP_LOCATION = application-operator-integ-cluster-dump
+endif
+
 .PHONY: build
 build: go-fmt go-vet
 	go build -o bin/manager main.go
@@ -213,10 +219,10 @@ integ-test: create-cluster
 	kind load docker-image --name ${CLUSTER_NAME} ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
 
 	echo 'Install OAM runtime and Verrazzano application operator...'
-	installer/install.sh || (echo 'Application operator install failed, capturing kind cluster dump'; ../tools/scripts/k8s-dump-cluster.sh -d application-operator-integ-cluster-dump; exit 1)
+	installer/install.sh || (echo 'Application operator install failed, capturing kind cluster dump'; ../tools/scripts/k8s-dump-cluster.sh -d ${CLUSTER_DUMP_LOCATION}; exit 1)
 
 	echo 'Run tests...'
-	ginkgo -v --keepGoing -cover test/integ/... || (echo 'Application operator tests failed, capturing kind cluster dump'; ../tools/scripts/k8s-dump-cluster.sh -d application-operator-integ-cluster-dump; exit 1)
+	ginkgo -v --keepGoing -cover test/integ/... || (echo 'Application operator tests failed, capturing kind cluster dump'; ../tools/scripts/k8s-dump-cluster.sh -d ${CLUSTER_DUMP_LOCATION}; exit 1)
 
 .PHONY: create-cluster
 create-cluster:
